In [84]:
# list_of_files = [ "bmw_automotive_rag.txt",
#     "honda_automotive_rag.txt",
#     "hyundai_automotive_rag.txt",
#     "kia_automotive_rag.txt",
#     "mahindra_automotive_rag.txt",
#     "mercedes_automotive_rag.txt",
#     "nissan_automotive_rag.txt",
#     "tata_automotive_rag.txt",
#     "toyota_automotive_rag.txt",
#     "volkswagen_automotive_rag.txt"]

In [85]:
list_of_files =[
 "bangalore_travel_guide.txt",
    "chennai_travel_guide.txt",
    "delhi_travel_guide.txt",
    "dubai_travel_guide.txt",
    "goa_travel_guide.txt",
    "hyderabad_travel_guide.txt",
    "kochi_travel_guide.txt",
    "london_travel_guide.txt",
    "mumbai_travel_guide.txt",
    "singapore_travel_guide.txt"
]

In [86]:
# with open("/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/LargeFormatFiles/bmw_automotive_rag.txt","r",encoding="utf-8") as file:
#     content = file.read()

In [87]:
with open("/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt","r",encoding="utf-8") as file:
    content = file.read()

In [88]:
all_content = []
for file in list_of_files:
    with open("/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/{}".format(file), "r", encoding="utf-8") as file:
        content =file.read()
        all_content.append({"id": file.name, "text":content})

In [89]:
all_content

[{'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': "BANGALORE TRAVEL GUIDE\nCity/Country: Bengaluru (Bangalore), Karnataka, India\nOverview: Major technology and startup hub known for parks, gardens, food, breweries and a relatively moderate climate.\nHistorical note: Bengaluru was founded by Kempegowda in 1537 and later developed under several kingdoms and British administration.\nBest months: October to February for pleasant weather and outdoor sightseeing.\nWeather: Usually milder than many Indian metros; April-May can be warm and monsoon periods bring rain.\nTop attractions: Bengaluru Palace, Lalbagh Botanical Garden, Cubbon Park, Vidhana Soudha, Tipu Sultan's Summer Palace, Bull Temple and Church Street.\nNearby attractions: Nandi Hills, Mysuru, Ramanagara and Shivanasamudra are popular excursions.\nSuggested opening hours: Parks and monuments have different schedules; verify before visiting.\nTicket prices: Parks may have low entry fees; palaces and museums generally charge admission.\nRestaurants/Food: Try masala dosa, benne dosa, idli-vada, filter coffee, Karnataka meals and diverse international cuisine.\nRestaurant areas: Indiranagar, Koramangala, MG Road, Church Street, Brigade Road and Jayanagar.\nHotels: Budget to luxury options are common around MG Road, Indiranagar, Koramangala, Whitefield and the airport corridor.\nTransportation: Namma Metro, BMTC buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Kempegowda International Airport is about 35-45 km from central areas depending on the destination.\nDistance example: Bengaluru to Mysuru is roughly 145 km by road.\nDistance example: Bengaluru to Nandi Hills is roughly 60 km from central Bengaluru.\nSafety: Traffic can be heavy; use marked crossings, trusted transport and normal urban precautions.\nBudget estimate: Budget INR 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day idea: Day 1 Lalbagh, Cubbon Park and MG Road; Day 2 Palace and heritage sites; Day 3 Nandi Hills or a nearby excursion.\nRAG facts: Founded in 1537; major tech hub; airport roughly 35-45 km from central areas.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': 'CHENNAI TRAVEL GUIDE\nCity/Country: Chennai, Tamil Nadu, India\nOverview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.\nHistorical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.\nBest months: November to February for relatively cooler sightseeing weather.\nWeather: Hot and humid for much of the year; June to September can bring southwest-monsoon rain and October to December can bring northeast-monsoon rain.\nTop attractions: Marina Beach, Fort St. George, Kapaleeshwarar Temple, Government Museum, San Thome Basilica, Valluvar Kottam and Besant Nagar Beach.\nLocal attraction detail: Marina Beach is about 12 km long and is popular around sunrise and in the evening.\nSuggested opening hours: Beaches are open-access areas; museums, forts and temples have their own schedules and may close on specific days.\nTicket prices: Marina Beach is free; paid attractions vary, so verify current official prices before travel.\nRestaurants/Food: Try South Indian breakfast, filter coffee, idli, dosa, pongal, Chettinad dishes and seafood.\nRestaurant areas: Mylapore, T. Nagar, Nungambakkam, Anna Nagar and Besant Nagar.\nHotels: Budget, business and luxury hotels are available near T. Nagar, Egmore, Nungambakkam, OMR and the airport corridor.\nTransportation: Chennai Metro, MTC buses, suburban rail, taxis, auto-rickshaws and app-based cabs.\nAirport: Chennai International Airport serves domestic and international routes.\nDistance example: Airport to central Chennai is roughly 15-20 km depending on the destination.\nDistance example: Chennai to Mahabalipuram is about 55-60 km by road.\nSafety: Use licensed/app-based transport, protect valuables in crowded places and be cautious near the sea.\nBudget estimate: Budget traveller INR 2,000-4,000/day; mid-range INR 5,000-10,000/day excluding major shopping.\n3-day idea: Day 1 Marina Beach and Fort St. George; Day 2 Mylapore and museums; Day 3 Besant Nagar or Mahabalipuram day trip.\nRAG facts: Coastal city; Bay of Bengal; Marina Beach about 12 km; best months November-February.\n'},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': "DELHI TRAVEL GUIDE\nCity/Country: Delhi, India\nOverview: India's national capital territory with Mughal, Sultanate, colonial and modern heritage.\nHistorical note: Delhi has been associated with several historic cities and empires, making it one of South Asia's major heritage destinations.\nBest months: October to March; winter sightseeing is popular, although fog and air quality can affect travel.\nWeather: Very hot summers, monsoon rain from roughly July to September and cool winters.\nTop attractions: Red Fort, India Gate, Qutub Minar, Humayun's Tomb, Lotus Temple, Akshardham and Jama Masjid.\nLocal attraction detail: Qutub Minar and Humayun's Tomb are major UNESCO-recognized heritage sites.\nSuggested opening hours: Each monument has its own schedule and weekly closure rules; verify before visiting.\nTicket prices: Many major monuments charge entry; prices can differ for Indian and foreign visitors.\nRestaurants/Food: Try chaat, parathas, kebabs, butter chicken, chole bhature and Old Delhi sweets.\nRestaurant areas: Connaught Place, Old Delhi, Khan Market, Hauz Khas and Aerocity.\nHotels: Budget to luxury options are available in Paharganj, Connaught Place, Karol Bagh, Aerocity and South Delhi.\nTransportation: Delhi Metro, buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Indira Gandhi International Airport is roughly 15-20 km from central Delhi depending on the destination.\nDistance example: India Gate to Connaught Place is roughly 2-3 km.\nDistance example: Central Delhi to Qutub Minar is roughly 15-20 km depending on the route.\nSafety: Avoid unofficial taxi offers, keep valuables secure and use extra caution late at night in unfamiliar areas.\nBudget estimate: Budget INR 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day idea: Day 1 central Delhi; Day 2 Old Delhi; Day 3 Qutub Minar, Humayun's Tomb and South Delhi.\nRAG facts: National capital; major Mughal and colonial heritage; best months October-March.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': "DUBAI TRAVEL GUIDE\nCity/Country: Dubai, United Arab Emirates\nOverview: Major Gulf city known for modern skyscrapers, luxury tourism, shopping, desert experiences and historic trading districts.\nHistorical note: Dubai developed from a small trading and pearling settlement into a global business and tourism centre, especially after oil-era growth and diversification.\nBest months: November to March for more comfortable outdoor sightseeing.\nWeather: Very hot summers; winters are warm and more suitable for outdoor activities.\nTop attractions: Burj Khalifa, Dubai Mall, Dubai Fountain area, Palm Jumeirah, Burj Al Arab views, Dubai Marina, Al Fahidi Historical District and desert safaris.\nLocal attraction detail: Burj Khalifa is one of Dubai's most famous landmarks and observation-deck visits use timed tickets.\nSuggested opening hours: Major attractions have individual schedules; malls generally stay open late.\nTicket prices: Public beaches can be free or low cost; major attractions and desert tours are paid and prices vary by package and time.\nRestaurants/Food: Wide international choice; try Emirati dishes, Arabic grills, shawarma, mezze and global cuisine.\nRestaurant areas: Downtown Dubai, Dubai Marina, JBR, Deira, Al Seef and DIFC.\nHotels: Budget to ultra-luxury options are available in Deira, Downtown, Marina, JBR, Business Bay and near the airport.\nTransportation: Dubai Metro, trams, buses, taxis and ride-hailing; Nol cards are used across major public transport.\nAirport: Dubai International Airport is roughly 15 km from Downtown Dubai by road.\nDistance example: Downtown Dubai to Dubai Marina is roughly 20-25 km by road.\nDistance example: Dubai Airport to Palm Jumeirah is roughly 30 km by road.\nSafety: Generally considered safe; respect local laws, dress expectations in appropriate places and summer heat precautions.\nBudget estimate: Budget AED 300-600/day; mid-range AED 800-1,500/day.\n3-day idea: Day 1 Downtown; Day 2 Old Dubai and Marina; Day 3 Palm Jumeirah or desert safari.\nRAG facts: Best months November-March; airport to Downtown roughly 15 km; major public transport includes Metro and trams.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': "GOA TRAVEL GUIDE\nRegion/Country: Goa, India\nOverview: India's smallest state by area, famous for beaches, Portuguese-influenced heritage, churches, cuisine and coastal tourism.\nHistorical note: Goa was ruled by Portugal for centuries before joining India in 1961.\nBest months: November to February for beach activities and relatively dry weather.\nWeather: Tropical; June to September is the main monsoon period with heavy rain.\nTop attractions: Baga Beach, Calangute Beach, Anjuna, Palolem, Old Goa churches, Basilica of Bom Jesus, Dudhsagar Falls and Panaji.\nLocal attraction detail: Old Goa is known for major churches and colonial-era heritage.\nSuggested opening hours: Beaches are open-access; churches, museums and wildlife attractions have individual schedules.\nTicket prices: Beaches are generally free; water sports, museums, guided tours and some attractions are paid.\nRestaurants/Food: Try Goan fish curry, vindaloo, xacuti, bebinca and local seafood.\nRestaurant areas: Panaji, Candolim, Baga, Calangute, Anjuna, Vagator and Palolem.\nHotels: Budget guesthouses, resorts and luxury hotels are available across North and South Goa.\nTransportation: Taxis, rental cars, scooters, buses and airport transfers are commonly used.\nAirport: Goa has Manohar International Airport at Mopa and Dabolim Airport serving different parts of the state.\nDistance example: Panaji to Calangute is roughly 15 km by road.\nDistance example: Panaji to Palolem is roughly 70 km by road.\nSafety: Use licensed water-sport operators, avoid swimming in dangerous sea conditions and do not drink and drive.\nBudget estimate: Budget INR 3,000-6,000/day; mid-range INR 7,000-15,000/day.\n3-day idea: Day 1 North Goa beaches; Day 2 Old Goa and Panaji; Day 3 South Goa beaches or Dudhsagar excursion.\nRAG facts: Portuguese rule ended with Goa joining India in 1961; best months November-February.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt',
  'text': 'HYDERABAD TRAVEL GUIDE\nCity/Country: Hyderabad, Telangana, India\nOverview: Historic Deccan city known for Nizami heritage, biryani, technology districts and a blend of old and modern Hyderabad.\nHistorical note: Hyderabad was founded in 1591 and the Charminar became one of its best-known symbols.\nBest months: October to February for more comfortable sightseeing.\nWeather: Hot summers; monsoon rain generally arrives during the middle of the year.\nTop attractions: Charminar, Golconda Fort, Salar Jung Museum, Hussain Sagar, Chowmahalla Palace, Mecca Masjid and Ramoji Film City.\nLocal attraction detail: Charminar was built in 1591 and is a central landmark of the old city.\nSuggested opening hours: Monuments and museums have individual schedules; verify before travel.\nTicket prices: Charminar area is free to explore; museums, forts and Ramoji Film City charge admission.\nRestaurants/Food: Try Hyderabadi biryani, haleem in season, kebabs, mirchi ka salan and Irani chai.\nRestaurant areas: Old City, Banjara Hills, Jubilee Hills, Hitech City and Gachibowli.\nHotels: Budget to luxury options are available around Banjara Hills, Hitech City, Gachibowli, Secunderabad and near the airport.\nTransportation: Hyderabad Metro, TSRTC buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Rajiv Gandhi International Airport is roughly 25-30 km from central Hyderabad depending on the destination.\nDistance example: Charminar to Golconda Fort is roughly 10-12 km by road.\nDistance example: Charminar to Hussain Sagar is roughly 6-8 km by road.\nSafety: Use normal urban precautions and expect crowds around major old-city markets.\nBudget estimate: Budget INR 2,000-4,500/day; mid-range INR 5,000-10,000/day.\n3-day idea: Day 1 Charminar and old city; Day 2 Golconda and museums; Day 3 Hussain Sagar and modern Hyderabad.\nRAG facts: Founded in 1591; Charminar is a central landmark; best months October-February.\n'},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt',
  'text': "KOCHI TRAVEL GUIDE\nCity/Country: Kochi (Cochin), Kerala, India\nOverview: Historic port city on India's southwest coast known for maritime trade, backwaters, colonial architecture and multicultural heritage.\nHistorical note: Kochi became an important spice-trade centre influenced by Indian, Arab, Portuguese, Dutch and British connections.\nBest months: October to March for relatively comfortable sightseeing.\nWeather: Tropical and humid; southwest monsoon brings heavy rain roughly from June onward.\nTop attractions: Fort Kochi, Chinese Fishing Nets, Mattancherry Palace, Jew Town, Paradesi Synagogue area, Marine Drive and Kerala backwater excursions.\nLocal attraction detail: Fort Kochi is known for colonial streets and waterfront views.\nSuggested opening hours: Outdoor waterfront areas are flexible; museums and heritage buildings have individual schedules.\nTicket prices: Walking Fort Kochi is largely free; museums, palaces and boat trips may charge admission.\nRestaurants/Food: Try appam and stew, seafood, Kerala meals, puttu, fish curry and local spices.\nRestaurant areas: Fort Kochi, Mattancherry, Panampilly Nagar, Marine Drive and Kakkanad.\nHotels: Heritage stays are popular in Fort Kochi; business hotels are common in Ernakulam and Kakkanad.\nTransportation: Ferries, Kochi Metro, buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Cochin International Airport is roughly 35-45 km from Fort Kochi depending on route and traffic.\nDistance example: Fort Kochi to Mattancherry is roughly 3-5 km.\nDistance example: Fort Kochi to Ernakulam city centre is roughly 10-15 km depending on the route.\nSafety: Use standard city precautions; monsoon conditions can affect ferry and road travel.\nBudget estimate: Budget INR 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day idea: Day 1 Fort Kochi; Day 2 Mattancherry and Jew Town; Day 3 backwater or island excursion.\nRAG facts: Historic spice-trade port; strong Portuguese, Dutch and British heritage; best months October-March.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt',
  'text': "LONDON TRAVEL GUIDE\nCity/Country: London, United Kingdom\nOverview: Capital of the United Kingdom and a major global centre for history, culture, finance, theatre and museums.\nHistorical note: London developed from Roman Londinium and later became a major political, commercial and imperial capital.\nBest months: May to September for longer daylight and generally milder weather, though rain is possible year-round.\nWeather: Temperate oceanic climate; winters are cool and summers are usually mild to warm.\nTop attractions: Tower of London, Buckingham Palace, British Museum, Westminster Abbey, Houses of Parliament, London Eye, Tower Bridge and Hyde Park.\nLocal attraction detail: Many major national museums offer free general admission, while special exhibitions may be paid.\nSuggested opening hours: Museums and attractions have individual schedules; advance booking may be required for popular sites.\nTicket prices: Several museums are free; attractions such as the Tower of London and London Eye require paid tickets.\nRestaurants/Food: Try fish and chips, Sunday roast, pies and London's highly diverse international food.\nRestaurant areas: Soho, Covent Garden, Borough Market, Shoreditch, South Bank and Camden.\nHotels: Budget to luxury options are available across Zones 1-3; good transport access can matter more than staying beside a landmark.\nTransportation: London Underground, buses, Overground, Elizabeth line, taxis and walking.\nAirport: Heathrow is roughly 25-30 km west of central London by road; rail travel can be quicker than road depending on traffic.\nDistance example: Westminster to Buckingham Palace is about 1 km.\nDistance example: Trafalgar Square to Covent Garden is about 1 km.\nSafety: Use normal big-city precautions, watch belongings in crowded transport and use licensed transport.\nBudget estimate: Budget GBP 120-220/day; mid-range GBP 250-450/day excluding major shopping.\n3-day idea: Day 1 Westminster and South Bank; Day 2 British Museum and Covent Garden; Day 3 Tower of London and East/Central London.\nRAG facts: Roman Londinium; several major museums have free general admission; Heathrow roughly 25-30 km from central London by road.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt',
  'text': "MUMBAI TRAVEL GUIDE\nCity/Country: Mumbai, Maharashtra, India\nOverview: India's financial and entertainment capital on the Arabian Sea, combining colonial heritage, beaches, business and Bollywood culture.\nHistorical note: Mumbai developed from a group of seven islands and became a major port and commercial centre.\nBest months: October to February for relatively pleasant sightseeing weather.\nWeather: Hot and humid in summer; June to September is monsoon season with heavy rain.\nTop attractions: Gateway of India, Marine Drive, Chhatrapati Shivaji Maharaj Terminus, Elephanta Caves, Siddhivinayak Temple, Haji Ali and Juhu Beach.\nLocal attraction detail: Gateway of India is a major waterfront landmark near Colaba.\nSuggested opening hours: Outdoor promenades are generally accessible; monuments, museums and caves have individual schedules.\nTicket prices: Marine Drive and Gateway viewing are free; Elephanta ferry and cave access are paid.\nRestaurants/Food: Try vada pav, pav bhaji, bhel puri, seafood, Parsi food and Maharashtrian dishes.\nRestaurant areas: Colaba, Fort, Bandra, Lower Parel, Juhu and Kala Ghoda.\nHotels: Budget to luxury stays are available in Colaba, Fort, Bandra, Andheri and near the airport.\nTransportation: Mumbai local trains, Metro, buses, taxis, auto-rickshaws in suburbs and app-based cabs.\nAirport: Chhatrapati Shivaji Maharaj International Airport is roughly 30 km from CST/CSMT according to district tourism information.\nDistance example: Gateway of India to Marine Drive is about 4-5 km by road.\nDistance example: South Mumbai to Juhu can take substantial time because of traffic.\nSafety: Crowded trains and markets require extra attention to belongings; monsoon travel may face flooding and delays.\nBudget estimate: Budget INR 3,000-6,000/day; mid-range INR 8,000-15,000/day.\n3-day idea: Day 1 Colaba and Marine Drive; Day 2 heritage Mumbai; Day 3 Elephanta Caves or Bandra/Juhu.\nRAG facts: Arabian Sea; former seven islands; best months October-February; airport roughly 30 km from CST/CSMT.\n"},
 {'id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt',

In [90]:
from wk06_pipeline import (
    CORPUS,
    chunk_documents,
    build_index,
    retrieve,
    ask_rag,
    cost_usd,
    DEFAULT_SYSTEM,
)

In [91]:
# chunks = chunk_documents(all_content, size = 4000, overlap = 600)

chunks = chunk_documents(all_content, size = 400, overlap = 60)

In [92]:
chunks

[{'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': 'BANGALORE TRAVEL GUIDE\nCity/Country: Bengaluru (Bangalore), Karnataka, India\nOverview: Major technology and startup hub known for parks, gardens, food, breweries and a relatively moderate climate.\nHistorical note: Bengaluru was founded by Kempegowda in 1537 and later developed under several kingdoms and British administration.\nBest months: October to February for pleasant weather and outdoor sight'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': ": October to February for pleasant weather and outdoor sightseeing.\nWeather: Usually milder than many Indian metros; April-May can be warm and monsoon periods bring rain.\nTop attractions: Bengaluru Palace, Lalbagh Botanical Garden, Cubbon Park, Vidhana Soudha, Tipu Sultan's Summer Palace, Bull Temple and Church Street.\nNearby attractions: Nandi Hills, Mysuru, Ramanagara and Shivanasamudra are popu"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#2',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': ' Nandi Hills, Mysuru, Ramanagara and Shivanasamudra are popular excursions.\nSuggested opening hours: Parks and monuments have different schedules; verify before visiting.\nTicket prices: Parks may have low entry fees; palaces and museums generally charge admission.\nRestaurants/Food: Try masala dosa, benne dosa, idli-vada, filter coffee, Karnataka meals and diverse international cuisine.\nRestaurant '},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#3',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': 'rnataka meals and diverse international cuisine.\nRestaurant areas: Indiranagar, Koramangala, MG Road, Church Street, Brigade Road and Jayanagar.\nHotels: Budget to luxury options are common around MG Road, Indiranagar, Koramangala, Whitefield and the airport corridor.\nTransportation: Namma Metro, BMTC buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Kempegowda International Airport is abou'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#4',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': 'ased cabs.\nAirport: Kempegowda International Airport is about 35-45 km from central areas depending on the destination.\nDistance example: Bengaluru to Mysuru is roughly 145 km by road.\nDistance example: Bengaluru to Nandi Hills is roughly 60 km from central Bengaluru.\nSafety: Traffic can be heavy; use marked crossings, trusted transport and normal urban precautions.\nBudget estimate: Budget INR 2,5'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#5',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': 'nd normal urban precautions.\nBudget estimate: Budget INR 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day idea: Day 1 Lalbagh, Cubbon Park and MG Road; Day 2 Palace and heritage sites; Day 3 Nandi Hills or a nearby excursion.\nRAG facts: Founded in 1537; major tech hub; airport roughly 35-45 km from central areas.\n'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': 'CHENNAI TRAVEL GUIDE\nCity/Country: Chennai, Tamil Nadu, India\nOverview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.\nHistorical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.\nBest months: November to February for relatively cooler sightseeing wea'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': ': November to February for relatively cooler sightseeing weather.\nWeather: Hot and humid for much of the year; June to September can bring southwest-monsoon rain and October to December can bring northeast-monsoon rain.\nTop attractions: Marina Beach, Fort St. George, Kapaleeshwarar Temple, Government Museum, San Thome Basilica, Valluvar Kottam and Besant Nagar Beach.\nLocal attraction detail: Marin'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#2',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': 'ottam and Besant Nagar Beach.\nLocal attraction detail: Marina Beach is about 12 km long and is popular around sunrise and in the evening.\nSuggested opening hours: Beaches are open-access areas; museums, forts and temples have their own schedules and may close on specific days.\nTicket prices: Marina Beach is free; paid attractions vary, so verify current official prices before travel.\nRestaurants/F'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#3',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': ' verify current official prices before travel.\nRestaurants/Food: Try South Indian breakfast, filter coffee, idli, dosa, pongal, Chettinad dishes and seafood.\nRestaurant areas: Mylapore, T. Nagar, Nungambakkam, Anna Nagar and Besant Nagar.\nHotels: Budget, business and luxury hotels are available near T. Nagar, Egmore, Nungambakkam, OMR and the airport corridor.\nTransportation: Chennai Metro, MTC bu'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#4',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': ' the airport corridor.\nTransportation: Chennai Metro, MTC buses, suburban rail, taxis, auto-rickshaws and app-based cabs.\nAirport: Chennai International Airport serves domestic and international routes.\nDistance example: Airport to central Chennai is roughly 15-20 km depending on the destination.\nDistance example: Chennai to Mahabalipuram is about 55-60 km by road.\nSafety: Use licensed/app-based t'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#5',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': ' is about 55-60 km by road.\nSafety: Use licensed/app-based transport, protect valuables in crowded places and be cautious near the sea.\nBudget estimate: Budget traveller INR 2,000-4,000/day; mid-range INR 5,000-10,000/day excluding major shopping.\n3-day idea: Day 1 Marina Beach and Fort St. George; Day 2 Mylapore and museums; Day 3 Besant Nagar or Mahabalipuram day trip.\nRAG facts: Coastal city; B'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#6',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': ' Nagar or Mahabalipuram day trip.\nRAG facts: Coastal city; Bay of Bengal; Marina Beach about 12 km; best months November-February.\n'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': "DELHI TRAVEL GUIDE\nCity/Country: Delhi, India\nOverview: India's national capital territory with Mughal, Sultanate, colonial and modern heritage.\nHistorical note: Delhi has been associated with several historic cities and empires, making it one of South Asia's major heritage destinations.\nBest months: October to March; winter sightseeing is popular, although fog and air quality can affect travel.\nW"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': "s popular, although fog and air quality can affect travel.\nWeather: Very hot summers, monsoon rain from roughly July to September and cool winters.\nTop attractions: Red Fort, India Gate, Qutub Minar, Humayun's Tomb, Lotus Temple, Akshardham and Jama Masjid.\nLocal attraction detail: Qutub Minar and Humayun's Tomb are major UNESCO-recognized heritage sites.\nSuggested opening hours: Each monument has"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#2',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': 'd heritage sites.\nSuggested opening hours: Each monument has its own schedule and weekly closure rules; verify before visiting.\nTicket prices: Many major monuments charge entry; prices can differ for Indian and foreign visitors.\nRestaurants/Food: Try chaat, parathas, kebabs, butter chicken, chole bhature and Old Delhi sweets.\nRestaurant areas: Connaught Place, Old Delhi, Khan Market, Hauz Khas and'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#3',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': 'reas: Connaught Place, Old Delhi, Khan Market, Hauz Khas and Aerocity.\nHotels: Budget to luxury options are available in Paharganj, Connaught Place, Karol Bagh, Aerocity and South Delhi.\nTransportation: Delhi Metro, buses, taxis, auto-rickshaws and app-based cabs.\nAirport: Indira Gandhi International Airport is roughly 15-20 km from central Delhi depending on the destination.\nDistance example: Ind'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#4',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': 'al Delhi depending on the destination.\nDistance example: India Gate to Connaught Place is roughly 2-3 km.\nDistance example: Central Delhi to Qutub Minar is roughly 15-20 km depending on the route.\nSafety: Avoid unofficial taxi offers, keep valuables secure and use extra caution late at night in unfamiliar areas.\nBudget estimate: Budget INR 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day ide'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#5',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt',
  'text': "R 2,500-5,000/day; mid-range INR 6,000-12,000/day.\n3-day idea: Day 1 central Delhi; Day 2 Old Delhi; Day 3 Qutub Minar, Humayun's Tomb and South Delhi.\nRAG facts: National capital; major Mughal and colonial heritage; best months October-March.\n"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'DUBAI TRAVEL GUIDE\nCity/Country: Dubai, United Arab Emirates\nOverview: Major Gulf city known for modern skyscrapers, luxury tourism, shopping, desert experiences and historic trading districts.\nHistorical note: Dubai developed from a small trading and pearling settlement into a global business and tourism centre, especially after oil-era growth and diversification.\nBest months: November to March f'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'growth and diversification.\nBest months: November to March for more comfortable outdoor sightseeing.\nWeather: Very hot summers; winters are warm and more suitable for outdoor activities.\nTop attractions: Burj Khalifa, Dubai Mall, Dubai Fountain area, Palm Jumeirah, Burj Al Arab views, Dubai Marina, Al Fahidi Historical District and desert safaris.\nLocal attraction detail: Burj Khalifa is one of Du'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#2',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': " safaris.\nLocal attraction detail: Burj Khalifa is one of Dubai's most famous landmarks and observation-deck visits use timed tickets.\nSuggested opening hours: Major attractions have individual schedules; malls generally stay open late.\nTicket prices: Public beaches can be free or low cost; major attractions and desert tours are paid and prices vary by package and time.\nRestaurants/Food: Wide inte"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#3',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'prices vary by package and time.\nRestaurants/Food: Wide international choice; try Emirati dishes, Arabic grills, shawarma, mezze and global cuisine.\nRestaurant areas: Downtown Dubai, Dubai Marina, JBR, Deira, Al Seef and DIFC.\nHotels: Budget to ultra-luxury options are available in Deira, Downtown, Marina, JBR, Business Bay and near the airport.\nTransportation: Dubai Metro, trams, buses, taxis and'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#4',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'irport.\nTransportation: Dubai Metro, trams, buses, taxis and ride-hailing; Nol cards are used across major public transport.\nAirport: Dubai International Airport is roughly 15 km from Downtown Dubai by road.\nDistance example: Downtown Dubai to Dubai Marina is roughly 20-25 km by road.\nDistance example: Dubai Airport to Palm Jumeirah is roughly 30 km by road.\nSafety: Generally considered safe; resp'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#5',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'ughly 30 km by road.\nSafety: Generally considered safe; respect local laws, dress expectations in appropriate places and summer heat precautions.\nBudget estimate: Budget AED 300-600/day; mid-range AED 800-1,500/day.\n3-day idea: Day 1 Downtown; Day 2 Old Dubai and Marina; Day 3 Palm Jumeirah or desert safari.\nRAG facts: Best months November-March; airport to Downtown roughly 15 km; major public tra'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#6',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt',
  'text': 'r-March; airport to Downtown roughly 15 km; major public transport includes Metro and trams.\n'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': "GOA TRAVEL GUIDE\nRegion/Country: Goa, India\nOverview: India's smallest state by area, famous for beaches, Portuguese-influenced heritage, churches, cuisine and coastal tourism.\nHistorical note: Goa was ruled by Portugal for centuries before joining India in 1961.\nBest months: November to February for beach activities and relatively dry weather.\nWeather: Tropical; June to September is the main mons"},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': 'ather.\nWeather: Tropical; June to September is the main monsoon period with heavy rain.\nTop attractions: Baga Beach, Calangute Beach, Anjuna, Palolem, Old Goa churches, Basilica of Bom Jesus, Dudhsagar Falls and Panaji.\nLocal attraction detail: Old Goa is known for major churches and colonial-era heritage.\nSuggested opening hours: Beaches are open-access; churches, museums and wildlife attractions'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#2',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': ' are open-access; churches, museums and wildlife attractions have individual schedules.\nTicket prices: Beaches are generally free; water sports, museums, guided tours and some attractions are paid.\nRestaurants/Food: Try Goan fish curry, vindaloo, xacuti, bebinca and local seafood.\nRestaurant areas: Panaji, Candolim, Baga, Calangute, Anjuna, Vagator and Palolem.\nHotels: Budget guesthouses, resorts '},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#3',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': 'a, Vagator and Palolem.\nHotels: Budget guesthouses, resorts and luxury hotels are available across North and South Goa.\nTransportation: Taxis, rental cars, scooters, buses and airport transfers are commonly used.\nAirport: Goa has Manohar International Airport at Mopa and Dabolim Airport serving different parts of the state.\nDistance example: Panaji to Calangute is roughly 15 km by road.\nDistance e'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#4',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': 'le: Panaji to Calangute is roughly 15 km by road.\nDistance example: Panaji to Palolem is roughly 70 km by road.\nSafety: Use licensed water-sport operators, avoid swimming in dangerous sea conditions and do not drink and drive.\nBudget estimate: Budget INR 3,000-6,000/day; mid-range INR 7,000-15,000/day.\n3-day idea: Day 1 North Goa beaches; Day 2 Old Goa and Panaji; Day 3 South Goa beaches or Dudhsa'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#5',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt',
  'text': ' Day 2 Old Goa and Panaji; Day 3 South Goa beaches or Dudhsagar excursion.\nRAG facts: Portuguese rule ended with Goa joining India in 1961; best months November-February.\n'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt',
  'text': 'HYDERABAD TRAVEL GUIDE\nCity/Country: Hyderabad, Telangana, India\nOverview: Historic Deccan city known for Nizami heritage, biryani, technology districts and a blend of old and modern Hyderabad.\nHistorical note: Hyderabad was founded in 1591 and the Charminar became one of its best-known symbols.\nBest months: October to February for more comfortable sightseeing.\nWeather: Hot summers; monsoon rain g'},
 {'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#1',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt',

In [93]:
chunks[0]

{'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#0',
 'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
 'text': 'BANGALORE TRAVEL GUIDE\nCity/Country: Bengaluru (Bangalore), Karnataka, India\nOverview: Major technology and startup hub known for parks, gardens, food, breweries and a relatively moderate climate.\nHistorical note: Bengaluru was founded by Kempegowda in 1537 and later developed under several kingdoms and British administration.\nBest months: October to February for pleasant weather and outdoor sight'}

In [94]:
len(chunks)

63

In [95]:
index = build_index(chunks)

In [96]:
index

[{'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt',
  'text': 'BANGALORE TRAVEL GUIDE\nCity/Country: Bengaluru (Bangalore), Karnataka, India\nOverview: Major technology and startup hub known for parks, gardens, food, breweries and a relatively moderate climate.\nHistorical note: Bengaluru was founded by Kempegowda in 1537 and later developed under several kingdoms and British administration.\nBest months: October to February for pleasant weather and outdoor sight',
  'vector': [-0.00467681884765625,
   -0.0009946823120117188,
   -0.006389617919921875,
   0.0037689208984375,
   -0.0406494140625,
   -0.033905029296875,
   -0.002559661865234375,
   0.0067901611328125,
   -0.0217132568359375,
   0.04510498046875,
   -0.0120391845703125,
   0.02618408203125,
   -0.01373291015625,
   -0.04693603515625,
   0.01812744140625,
   0.002552032470703125,
   -0.0297088623046875,
   -0.00414276123046875,
   -0.000850677490234375,
   0.0308380126953125,
   0.00124359130859375,
   0.00567626953125,
   -0.02923583984375,
   -0.01287078857421875,
   0.018402099609375,
   0.0390625,
   -0.046356201171875,
   0.0054473876953125,
   -0.0184173583984375,
   -0.0198211669921875,
   -0.00782012939453125,
   -0.01146697998046875,
   0.0284423828125,
   -0.037384033203125,
   0.034027099609375,
   0.01422119140625,
   0.04327392578125,
   -0.007537841796875,
   0.036529541015625,
   0.05352783203125,
   0.0101318359375,
   0.00582122802734375,
   0.0129852294921875,
   0.04107666015625,
   -0.0023937225341796875,
   0.0209808349609375,
   -0.061737060546875,
   0.032806396484375,
   -0.034088134765625,
   -0.0098419189453125,
   0.027252197265625,
   -0.043060302734375,
   -0.00010848045349121094,
   -0.0016469955444335938,
   0.0034160614013671875,
   -0.040618896484375,
   0.00843048095703125,
   0.00203704833984375,
   0.00612640380859375,
   -0.010772705078125,
   0.0242156982421875,
   0.01812744140625,
   0.0232391357421875,
   0.0181884765625,
   -0.0161590576171875,
   0.00936126708984375,
   -0.0099029541015625,
   -0.005054473876953125,
   0.0277557373046875,
   -0.01222991943359375,
   0.050048828125,
   0.040771484375,
   -0.0061798095703125,
   -0.0225830078125,
   0.004886627197265625,
   0.00620269775390625,
   0.01153564453125,
   -0.0017547607421875,
   0.0443115234375,
   -0.0200958251953125,
   -0.0418701171875,
   0.007171630859375,
   0.00891876220703125,
   0.00919342041015625,
   -0.02685546875,
   0.0077972412109375,
   0.0006031990051269531,
   -0.022674560546875,
   -0.0003428459167480469,
   -0.0005049705505371094,
   0.0411376953125,
   -0.036346435546875,
   0.0053253173828125,
   0.0284271240234375,
   0.0175933837890625,
   -0.0036258697509765625,
   0.006500244140625,
   -0.0152587890625,
   0.033905029296875,
   0.0782470703125,
   0.01419830322265625,
   -0.029296875,
   -0.012298583984375,
   0.0196533203125,
   0.06768798828125,
   -0.051483154296875,
   0.0298919677734375,
   0.02032470703125,
   0.0887451171875,
   0.03076171875,
   -0.0997314453125,
   0.0008006095886230469,
   0.01549530029296875,
   0.035736083984375,
   -0.01100921630859375,
   -0.02142333984375,
   0.054290771484375,
   -0.050628662109375,
   0.0277099609375,
   -0.0302581787109375,
   -0.01702880859375,
   0.004974365234375,
   -0.0116729736328125,
   -0.047119140625,
   -0.057098388671875,
   -0.0341796875,
   -0.00795745849609375,
   -0.0233612060546875,
   -0.01433563232421875,
   0.0248260498046875,
   0.007144927978515625,
   0.007366180419921875,
   -0.006816864013671875,
   0.005218505859375,
   0.01113128662109375,
   -0.0270233154296875,
   -0.02178955078125,
   0.0163726806640625,
   -0.00817108154296875,
   -0.0634765625,
   -0.003253936767578125,
   0.01174163818359375,
   -0.0185699462890625,
   0.0161895751953125,
   -0.02239990234375,
   -0.023162841796875,
   -0.02685546875,
   0.03265380859375,
   -0.005115509033203125,
   0.036041259765625,
   -0.0189666748046875,
   -0.006969451904296875,
   -0.044891357421875,
   0.01180267333984375,
   0.005748748779296875,
   -0.043914794921875,
   -0.005123138427734375,
   0.047119140625,
   -0.0304107666015625,
   -0.0287628173828125,
   -0.062347412109375,
   -0.0218963623046875,
   0.025299072265625,
   0.025848388671875,
   -0.0021991729736328125,
   0.0023670196533203125,
   -0.083251953125,
   0.004566192626953125,
   -0.036773681640625,
   -0.032928466796875,
   0.01091766357421875,
   -0.032684326171875,
   -0.00101470947265625,
   0.0517578125,
   -0.006435394287109375,
   0.0528564453125,
   -0.001567840576171875,
   -0.037261962890625,
   0.0108489990234375,
   -0.019744873046875,
   -0.02947998046875,
   -0.0190887451171875,
   -0.0014944076538085938,
   0.041717529296875,
   -0.0164031982421875,
   0.07080078125,
   -0.0273284912109375,
   -0.0302886962890625,
   -0.0457763671875,
   0.0175933837890625,
   -0.0294647216796875,
   -0.007114410400390625,
   -0.014556884765625,
   0.0010929107666015625,
   -0.00875091552734375,
   -0.04302978515625,
   -0.01458740234375,
   -0.0259857177734375,
   0.006252288818359375,
   0.01525115966796875,
   -0.0046234130859375,
   -0.02740478515625,
   0.02593994140625,
   0.025970458984375,
   -0.0287933349609375,
   -0.06854248046875,
   0.05242919921875,
   0.021209716796875,
   0.0179290771484375,
   0.00933837890625,
   0.01641845703125,
   -0.0233612060546875,
   -0.0209808349609375,
   0.00363922119140625,
   0.06744384765625,
   0.004116058349609375,
   -0.0587158203125,
   -0.0019254684448242188,
   -0.0228118896484375,
   0.019287109375,
   0.0105743408203125,
   0.022186279296875,
   0.01088714599609375,
   -0.005886077880859375,
   0.036376953125,
   0.01171112060546875,
   -0.0133819580078125,
   -0.0035953521728515625,
   -0.0022869110107421875,
   -0.0039215087890625,
   0.0499267578125,
   0.0121612548828125,
   -0.0168304443359375,
   -0.0098114013671875,
   0.005947113037109375,
   -0.01021575927734375,
   0.05096435546875,
   0.0163116455078125,
   -0.0092926025390625,
   -0.0158843994140625,
   -0.0157470703125,
   0.0102386474609375,
   -0.00402069091796875,
   0.00598907470703125,
   0.0169219970703125,
   0.004543304443359375,
   -0.01070404052734375,
   -0.02081298828125,
   0.0291900634765625,
   0.041595458984375,
   0.0108184814453125,
   -0.0022487640380859375,
   0.00832366943359375,
   -0.007476806640625,
   0.006008148193359375,
   -0.01171875,
   -0.01511383056640625,
   -0.02349853515625,
   0.0482177734375,
   -0.0860595703125,
   -0.01274871826171875,
   -0.0100555419921875,
   0.02294921875,
   -0.0621337890625,
   -0.010040283203125,
   0.00878143310546875,
   -0.00029587745666503906,
   -0.020751953125,
   -0.01555633544921875,
   -0.0853271484375,
   0.012298583984375,
   -0.00881195068359375,
   0.0010404586791992188,
   -0.057281494140625,
   -0.04083251953125,
   -0.006603240966796875,
   0.0287933349609375,
   -0.0052947998046875,
   -0.045257568359375,
   -0.0161285400390625,
   0.0225830078125,
   0.02154541015625,
   -0.004207611083984375,
   -0.0302886962890625,
   0.01560211181640625,
   -0.0009927749633789062,
   0.06890869140625,
   0.0244598388671875,
   -0.02496337890625,
   0.0062103271484375,
   0.04052734375,
   -0.05194091796875,
   0.00021195411682128906,
   -0.0033111572265625,
   0.01189422607421875,
   0.00867462158203125,
   0.00266265869140625,
   -0.01457977294921875,
   0.034637451171875,
   -0.0203857421875,
   -0.0036182403564453125,
   -0.044403076171875,
   -0.0294189453125,
   0.0158538818359375,
   -0.0108642578125,
   0.007411956787109375,
   -0.02734375,
   -0.01031494140625,
   -0.03936767578125,
   0.022247314453125,
   -0.00787353515625,
   -0.0172271728515625,
   0.0181427001953125,
   -0.0278167724609375,
   -0.0244140625,
   -0.033172607421875,
   0.0168304443359375,
   -0.0311431884765625,
   0.02081298828125,
   -0.007801055908203125,
   -0.00989532470703125,
   -0.0014715194702148438,
   0.015472412109375,
   -0.010101318359375,
   -0.0013141632080078125,
   0.005733489990234375,
   0.0015316009521484375,
   0.0287933349609375,
   0.0188751220703125,
   -0.04583740234375,
   -0.0125732421875,
   0.013153076171875,
   -0.06640625,
   0.034759521484375,
   -0.071044921875,
   -0.003917694091796875,
   -0.0266571044921875,
   0.03289794921875,
   -0.045623779296875,
   0.034912109375,
   0.0181732177734375,
   -0.03985595703125,
   -0.0255584716796875,
   -0.01399993896484375,
   -0.0033855438232421875,
   0.01800537109375,
   -0.031982421875,
   0.033111572265625,
   0.0009274482727050781,
   0.017913818359375,
   -0.038360595703125,
   0.001224517822265625,
   0.0006256103515625,
   0.0279541015625,
   -0.060272216796875,
   -0.042938232421875,
   0.025634765625,
   0.0303802490234375,
   -0.050994873046875,
   0.04449462890625,
   0.04388427734375,
   -0.034576416015625,
   0.041259765625,
   0.072509765625,
   0.0228271484375,
   -0.0015888214111328125,
   -0.08880615234375,
   -0.0124969482421875,
   -0.0772705078125,
   0.00505828857421875,
   0.0007028579711914062,
   -0.0073394775390625,
   0.00934600830078125,
   -0.01332855224609375,
   -0.0008544921875,
   -0.00019156932830810547,
   0.00925445556640625,
   -4.494190216064453e-05,
   0.0024242401123046875,
   0.03472900390625,
   0.039794921875,
   -0.00679779052734375,
   0.00963592529296875,
   -0.0290374755859375,
   0.019317626953125,
   0.0231170654296875,
   0.0080718994140625,
   -0.0281982421875,
   -0.007221221923828125,
   -0.007232666015625,
   -0.035003662109375,
   -0.00044608116149902344,
   0.004947662353515625,
   0.00803375244140625,
   0.0357666015625,
   0.004749298095703125,
   0.06317138671875,
   -0.03265380859375,
   0.00623321533203125,
   -0.006298065185546875,
   0.04022216796875,
   -0.043670654296875,
   0.0186004638671875,
   -0.0242767333984375,
   0.0116424560546875,
   -0.0234832763671875,
   -0.0169677734375,
   0.01555633544921875,
   -0.00577545166015625,
   -0.004581451416015625,
   0.005340576171875,
   -0.05426025390625,
   0.0186767578125,
   -0.00030350685119628906,
   -0.0445556640625,
   -0.0265350341796875,
   -0.01806640625,
   -0.0031280517578125,
   -0.01329803466796875,
   0.009796142578125,
   -0.0023059844970703125,
   -0.037811279296875,
   -0.0229949951171875,
   -0.0026607513427734375,
   -0.057830810546875,
   0.00910186767578125,
   0.00567626953125,
   0.015411376953125,
   -0.049774169921875,
   -0.022216796875,
   0.01122283935546875,
   -0.036895751953125,
   -0.0286102294921875,
   0.06610107421875,
   -0.0003447532653808594,
   0.0232391357421875,
   0.005115509033203125,
   -0.03143310546875,
   -0.021697998046875,
   0.01323699951171875,
   -0.0013275146484375,
   -0.03759765625,
   0.006866455078125,
   0.031890869140625,
   -0.0297698974609375,
   -0.010162353515625,
   -0.01641845703125,
   0.0570068359375,
   0.000926971435546875,
   -0.015838623046875,
   0.00925445556640625,
   -0.01020050048828125,
   -0.011322021484375,
   0.0066986083984375,
   -0.0163421630859375,
   0.00476837158203125,
   0.0058746337890625,
   -0.07281494140625,
   0.0251922607421875,
   0.0577392578125,
   -0.0023822784423828125,
   -0.0391845703125,
   -0.021270751953125,
   0.02239990234375,
   0.02081298828125,
   -0.00867462158203125,
   -0.05419921875,
   0.027191162109375,
   0.0180511474609375,
   -0.07147216796875,
   0.033294677734375,
   0.031890869140625,
   0.0088348388671875,
   0.0341796875,
   -0.01448822021484375,
   0.01519775390625,
   -0.0108489990234375,
   -0.0386962890625,
   0.00901031494140625,
   0.010406494140625,
   0.02001953125,
   -0.0172882080078125,
   -0.0290985107421875,
   0.00891876220703125,
   0.03948974609375,
   -0.0070343017578125,
   0.00540924072265625,
   0.031585693359375,
   0.01396942138671875,
   -0.0262298583984375,
   -0.0596923828125,
   -0.0025787353515625,
   0.05810546875,
   -0.00539398193359375,
   -0.0060882568359375,
   -0.0438232421875,
   -0.0765380859375,
   -0.027069091796875,
   0.0181121826171875,
   0.041046142578125,
   -0.0648193359375,
   -0.02685546875,
   -0.03411865234375,
   -0.042694091796875,
   0.012603759765625,
   -0.0002906322479248047,
   -0.00890350341796875,
   -0.036285400390625,
   -0.02191162109375,
   -0.07843017578125,
   -0.004459381103515625,
   -0.019073486328125,
   0.0005950927734375,
   -0.01372528076171875,
   0.0226898193359375,
   0.026214599609375,
   -0.018524169921875,
   0.03546142578125,
   -0.020172119140625,
   -0.0249481201171875,
   -0.007320404052734375,
   0.032562255859375,
   -0.041015625,
   0.0229339599609375,
   -0.00244140625,
   0.003177642822265625,
   0.0163421630859375,
   -0.0833740234375,
   0.00386810302734375,
   -0.019683837890625,
   -0.0186309814453125,
   0.005523681640625,
   -0.0110015869140625,
   0.0030879974365234375,
   0.00934600830078125,
   -0.0036678314208984375,
   -0.0032196044921875,
   -0.0164031982421875,
   -0.00473785400390625,
   -0.031341552734375,
   -0.004730224609375,
   -0.0023651123046875,
   0.02508544921875,
   -0.02935791015625,
   -0.0173187255859375,
   -0.007549285888671875,
   -0.0008363723754882812,
   0.0248260498046875,
   -0.0013637542724609375,
   0.0236663818359375,
   0.07635498046875,
   0.00797271728515625,
   0.0175933837890625,
   0.032684326171875,
   -0.0113677978515625,
   -0.0116729736328125,
   -0.0185089111328125,
   -0.0052642822265625,
   0.0212860107421875,
   -0.0224456787109375,
   -0.023681640625,
   -0.026336669921875,
   0.0118865966796875,
   0.0178375244140625,
   0.057037353515625,
   0.01557159423828125,
   0.018951416015625,
   -0.0031490325927734375,
   0.033843994140625,
   -0.01311492919921875,
   -0.0004608631134033203,
   -0.0131072998046875,
   -0.003376007080078125,
   -0.0301666259765625,
   0.0300750732421875,
   0.00437164306640625,
   0.021392822265625,
   -0.04498291015625,
   -0.05181884765625,
   0.0167999267578125,
   0.0171356201171875,
   0.0192718505859375,
   0.0010213851928710938,
   -0.006252288818359375,
   0.002635955810546875,
   0.02734375,
   0.0010251998901367188,
   0.01131439208984375,
   0.0005726814270019531,
   -0.03619384765625,
   -0.00995635986328125,
   -0.0419921875,
   -0.00992584228515625,
   -0.01401519775390625,
   -0.0002624988555908203,
   0.01049041748046875,
   -0.020538330078125,
   -0.0090484619140625,
   -0.045623779296875,
   0.03961181640625,
   0.01088714599609375,
   -0.0247039794921875,
   -0.04638671875,
   0.03741455078125,
   -0.01371002197265625,
   0.013031005859375,
   -0.026336669921875,
   -0.03271484375,
   -0.015625,
   -0.049774169921875,
   0.0107421875,
   -0.006862640380859375,
   -0.005336761474609375,
   0.006023406982421875,
   -0.0360107421875,
   -0.0304107666015625,
   0.0240936279296875,
   0.007526397705078125,
   0.033599853515625,
   0.00838470458984375,
   0.0276641845703125,
   0.00478363037109375,
   -0.0238037109375,
   0.0127105712890625,
   0.004367828369140625,
   0.0131988525390625,
   0.02813720703125,
   0.01500701904296875,
   -0.01119232177734375,
   -0.053192138671875,
   0.02093505859375,
   0.0390625,
   -0.031524658203125,
   -0.0179595947265625,
   0.00020194053649902344,
   0.007373809814453125,
   -0.00231170654296875,
   -0.02972412109375,
   0.0191192626953125,
   -0.027313232421875,
   0.0229339599609375,
   -0.019775390625,
   0.033355712890625,
   -0.0111846923828125,
   0.0328369140625,
   -0.014801025390625,
   -0.0025081634521484375,
   0.0291900634765625,
   0.044647216796875,
   -0.0121917724609375,
   0.002696990966796875,
   -0.006195068359375,
   -0.0124359130859375,
   0.0347900390625,
   0.0068511962890625,
   -0.006855010986328125,
   0.04254150390625,
   -0.02301025390625,
   -0.0199737548828125,
   0.041259765625,
   -0.007076263427734375,
   0.0016927719116210938,
   -0.05206298828125,
   -0.038665771484375,
   -0.0271453857421875,
   0.030517578125,
   0.037017822265625,
   -0.004375457763671875,
   0.01031494140625,
   0.0084075927734375,
   -0.00231170654296875,
   0.0100250244140625,
   -0.0006537437438964844,
   -0.0019159317016601562,
   0.01678466796875,
   0.01287078857421875,
   0.01427459716796875,
   -0.0249481201171875,
   -0.00908660888671875,
   0.033294677734375,
   0.01861572265625,
   -0.00402069091796875,
   -0.056884765625,
   0.035400390625,
   -0.0016231536865234375,
   0.0215911865234375,
   0.0308837890625,
   0.00963592529296875,
   0.0158538818359375,
   -0.0311126708984375,
   0.0382080078125,
   0.007747650146484375,
   0.0433349609375,
   0.01290130615234375,
   0.01385498046875,
   0.0132598876953125,
   0.00656890869140625,
   0.0225067138671875,
   0.0008673667907714844,
   -0.04327392578125,
   0.005229949951171875,
   0.04205322265625,
   0.033966064453125,
   -0.0300140380859375,
   0.00804901123046875,
   0.00969696044921875,
   -0.00884246826171875,
   -0.02679443359375,
   0.0034198760986328125,
   -0.02935791015625,
   -0.052215576171875,
   0.01529693603515625,
   0.01486968994140625,
   0.0191802978515625,
   0.0177764892578125,
   -0.001953125,
   0.00908660888671875,
   0.013427734375,
   -0.024749755859375,
   -0.01511383056640625,
   -0.0251922607421875,
   0.004840850830078125,
   0.002925872802734375,
   0.00826263427734375,
   0.00827789306640625,
   0.0281982421875,
   -0.00732421875,
   -0.014923095703125,
   -0.0172882080078125,
   -0.00635528564453125,
   0.02740478515625,
   -0.007053375244140625,
   0.020050048828125,
   0.009765625,
   -0.00545501708984375,
   3.8683414459228516e-05,
   -0.0264739990234375,
   -0.02911376953125,
   -0.0172882080078125,
   -0.03594970703125,
   0.0263519287109375,
   -0.0037288665771484375,
   -0.025146484375,
   0.00879669189453125,
   -0.01471710205078125,
   0.0013151168823242188,
   0.0034732818603515625,
   0.022979736328125,
   0.0023975372314453125,
   0.0014982223510742188,
   0.01499176025390625,
   0.002735137939453125,
   -0.00463104248046875,
   -0.00586700439453125,
   0.02685546875,
   0.01222991943359375,
   -0.005931854248046875,
   0.025970458984375,
   -0.0280609130859375,
   0.01666259765625,
   -0.02191162109375,
   0.0274658203125,
   -0.0009255409240722656,
   0.033172607421875,
   -0.00904083251953125,
   0.018035888671875,
   0.00920867919921875,
   0.03790283203125,
   0.0007338523864746094,
   -0.0297393798828125,
   0.037017822265625,
   -0.0117034912109375,
   0.00875091552734375,
   -0.005825042724609375,
   0.063232421875,
   0.04400634765625,
   -0.0298614501953125,
   0.0131683349609375,
   0.0007281303405761719,
   0.00980377197265625,
   0.02996826171875,
   0.01045989990234375,
   0.0037593841552734375,
   0.026641845703125,
   -0.031585693359375,
   0.013458251953125,
   0.034149169921875,
   -0.0197906494140625,
   -0.007343292236328125,
   0.00958251953125,
   -0.006072998046875,
   -0.00875091552734375,
   0.0172882080078125,
   -0.004817962646484375,
   -0.01058197021484375,
   0.034637451171875,
   -0.022918701171875,
   -0.04656982421875,
   0.007678985595703125,
   0.00951385498046875,
   0.060333251953125,
   0.007755279541015625,
   -0.01030731201171875,
   0.0162811279296875,
   0.0226287841796875,
   0.01971435546875,
   -0.044677734375,
   -0.01097869873046875,
   -0.02349853515625,
   -0.033294677734375,
   0.001953125,
   -0.035308837890625,
   0.01898193359375,
   0.01421356201171875,
   0.025634765625,
   -0.0116729736328125,
   0.0298614501953125,
   0.034698486328125,
   -0.0161285400390625,
   -0.00015842914581298828,
   0.0203094482421875,
   0.022552490234375,
   -0.04107666015625,
   0.0176544189453125,
   0.01519775390625,
   0.005535125732421875,
   0.00899505615234375,
   -0.025787353515625,
   -0.00791168212890625,
   -0.06927490234375,
   -0.0038127899169921875,
   0.031829833984375,
   0.021148681640625,
   0.0010728836059570312,
   0.011932373046875,
   0.018707275390625,
   0.011688232421875,
   -0.004734039306640625,

In [97]:
#query="How many vehicles did Toyota record as its principal 2025 vehicle volume?"
query = "What is the best month to visit Chennai from Chennai travel guide?"

In [98]:
retrived = retrieve(query,index)

In [99]:
retrived

[{'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0',
  'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
  'text': 'CHENNAI TRAVEL GUIDE\nCity/Country: Chennai, Tamil Nadu, India\nOverview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.\nHistorical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.\nBest months: November to February for relatively cooler sightseeing wea',
  'vector': [0.06964111328125,
   -0.004734039306640625,
   0.0294952392578125,
   0.0154571533203125,
   0.0009036064147949219,
   -0.0091552734375,
   0.03558349609375,
   -0.032958984375,
   -0.056671142578125,
   0.02978515625,
   -0.040985107421875,
   0.0214080810546875,
   -0.0082244873046875,
   0.0005888938903808594,
   0.026123046875,
   0.0303802490234375,
   -0.042938232421875,
   -0.01206207275390625,
   0.0202484130859375,
   0.044403076171875,
   0.052764892578125,
   0.01947021484375,
   -0.0069580078125,
   -0.05780029296875,
   0.0224151611328125,
   0.03564453125,
   -0.0208892822265625,
   0.0219573974609375,
   -0.0211029052734375,
   0.0024261474609375,
   -0.0012845993041992188,
   0.0032863616943359375,
   0.054962158203125,
   -0.01250457763671875,
   0.0285797119140625,
   0.005458831787109375,
   0.0227813720703125,
   -0.0198822021484375,
   -0.0208740234375,
   -0.003376007080078125,
   0.032958984375,
   0.040374755859375,
   0.0335693359375,
   0.04058837890625,
   -0.00283050537109375,
   -0.004535675048828125,
   -0.06219482421875,
   0.04833984375,
   0.006763458251953125,
   -0.0311279296875,
   -0.0028438568115234375,
   -0.03118896484375,
   -0.0137939453125,
   0.020721435546875,
   -0.007259368896484375,
   -0.040374755859375,
   0.0264434814453125,
   0.029632568359375,
   -0.00830841064453125,
   -0.0166473388671875,
   0.02783203125,
   -0.0098876953125,
   -0.00489044189453125,
   0.0300445556640625,
   0.01114654541015625,
   0.0250701904296875,
   -0.047576904296875,
   0.04791259765625,
   -0.01319122314453125,
   0.0026378631591796875,
   0.0655517578125,
   -0.00949859619140625,
   -0.0017242431640625,
   -0.0147552490234375,
   -0.030426025390625,
   0.04376220703125,
   -0.033172607421875,
   -0.036468505859375,
   0.027557373046875,
   -0.0308990478515625,
   -0.06402587890625,
   0.028961181640625,
   0.00443267822265625,
   0.0169219970703125,
   -0.052978515625,
   -0.0022335052490234375,
   0.060333251953125,
   0.0121917724609375,
   -0.018798828125,
   0.0262908935546875,
   0.0175628662109375,
   -0.02166748046875,
   0.0174407958984375,
   0.021026611328125,
   0.042938232421875,
   0.006649017333984375,
   0.01519775390625,
   0.0047149658203125,
   0.03045654296875,
   0.06005859375,
   0.01885986328125,
   -0.03466796875,
   -0.032562255859375,
   0.0032138824462890625,
   0.07061767578125,
   0.01293182373046875,
   -0.019622802734375,
   -0.0032215118408203125,
   0.016845703125,
   -0.02008056640625,
   -0.0684814453125,
   0.003925323486328125,
   0.0015878677368164062,
   0.03680419921875,
   -0.01233673095703125,
   -0.03173828125,
   0.060516357421875,
   -0.071533203125,
   -0.01122283935546875,
   0.01556396484375,
   -0.0280303955078125,
   -0.01332855224609375,
   0.007175445556640625,
   -0.01543426513671875,
   -0.0416259765625,
   -0.0697021484375,
   -0.0030364990234375,
   0.0308380126953125,
   0.0261383056640625,
   -0.0178985595703125,
   0.015228271484375,
   0.00927734375,
   -0.00980377197265625,
   -0.02947998046875,
   0.008758544921875,
   -0.03753662109375,
   -0.036041259765625,
   0.00026345252990722656,
   -0.01006317138671875,
   0.033050537109375,
   0.0313720703125,
   -0.01605224609375,
   -0.0181732177734375,
   0.0270538330078125,
   0.007083892822265625,
   -0.029388427734375,
   -0.032318115234375,
   0.0491943359375,
   0.0309600830078125,
   0.00432586669921875,
   0.0037441253662109375,
   0.0102996826171875,
   0.0205230712890625,
   0.00011754035949707031,
   0.0032978057861328125,
   -0.0238494873046875,
   -0.023773193359375,
   0.011627197265625,
   -0.049591064453125,
   -0.0254058837890625,
   -0.04266357421875,
   -0.009521484375,
   -0.0255279541015625,
   -0.004222869873046875,
   -0.01165008544921875,
   -0.0389404296875,
   -0.07958984375,
   0.0125732421875,
   -0.050079345703125,
   0.0181427001953125,
   0.0128173828125,
   -0.0180511474609375,
   0.0162811279296875,
   0.021575927734375,
   0.048492431640625,
   0.025146484375,
   0.0174560546875,
   -0.06829833984375,
   -0.054412841796875,
   -0.00039887428283691406,
   -0.041717529296875,
   -0.0033321380615234375,
   -0.0021457672119140625,
   -0.006198883056640625,
   0.0023632049560546875,
   0.015289306640625,
   -0.0012073516845703125,
   0.006259918212890625,
   -0.0194244384765625,
   0.0238189697265625,
   -0.0173797607421875,
   -0.01415252685546875,
   0.00350189208984375,
   -0.0017881393432617188,
   -0.02734375,
   -0.0272216796875,
   0.01491546630859375,
   -0.034271240234375,
   0.00508880615234375,
   -0.03125,
   0.024932861328125,
   -0.030029296875,
   -0.006168365478515625,
   0.010406494140625,
   -0.052215576171875,
   -0.0132293701171875,
   0.047271728515625,
   0.03106689453125,
   0.002777099609375,
   0.0237274169921875,
   0.035064697265625,
   -0.0189361572265625,
   -0.0207672119140625,
   -0.0178680419921875,
   0.0208282470703125,
   0.015716552734375,
   -0.04132080078125,
   -0.0357666015625,
   -0.0211334228515625,
   -0.02264404296875,
   -0.0265960693359375,
   0.005840301513671875,
   0.009033203125,
   0.00449371337890625,
   -0.006855010986328125,
   0.005725860595703125,
   -0.0330810546875,
   0.0288848876953125,
   0.01313018798828125,
   -0.038970947265625,
   0.00513458251953125,
   -0.032928466796875,
   0.0270843505859375,
   -0.0260467529296875,
   -0.0150299072265625,
   -0.0477294921875,
   0.0933837890625,
   0.0225372314453125,
   0.00579071044921875,
   -0.0195465087890625,
   -0.0477294921875,
   0.035308837890625,
   -0.0012302398681640625,
   0.015350341796875,
   0.01033782958984375,
   -0.0153656005859375,
   -0.013275146484375,
   -0.001598358154296875,
   0.025543212890625,
   0.0187530517578125,
   0.022369384765625,
   0.0367431640625,
   0.01255035400390625,
   -0.041168212890625,
   0.008697509765625,
   0.0150146484375,
   -0.0204925537109375,
   -0.010009765625,
   -0.0111541748046875,
   -0.051544189453125,
   -0.0306549072265625,
   0.0233917236328125,
   0.0145111083984375,
   -0.072265625,
   0.0032176971435546875,
   0.004451751708984375,
   -0.019744873046875,
   -0.005603790283203125,
   0.0006961822509765625,
   -0.045654296875,
   -0.0189361572265625,
   -0.020294189453125,
   0.008392333984375,
   -0.05657958984375,
   -0.0439453125,
   -0.010345458984375,
   -0.03692626953125,
   0.0022830963134765625,
   -0.0297088623046875,
   0.01561737060546875,
   0.0014600753784179688,
   0.00879669189453125,
   -0.0248565673828125,
   6.091594696044922e-05,
   -0.0311126708984375,
   0.00960540771484375,
   0.0284881591796875,
   -0.0015649795532226562,
   0.01377105712890625,
   -0.0024013519287109375,
   0.04278564453125,
   -0.020599365234375,
   -0.0099945068359375,
   0.0250396728515625,
   0.0221405029296875,
   0.00750732421875,
   -0.035125732421875,
   -0.01303863525390625,
   0.060089111328125,
   -0.036956787109375,
   -0.02679443359375,
   -0.006748199462890625,
   -0.044036865234375,
   -0.0154571533203125,
   0.005954742431640625,
   0.03173828125,
   -0.03192138671875,
   -0.01398468017578125,
   -0.00315093994140625,
   0.0301971435546875,
   -0.0175323486328125,
   -0.01181793212890625,
   0.0205230712890625,
   -0.03350830078125,
   -0.040435791015625,
   -0.0213623046875,
   0.00408172607421875,
   -0.00550079345703125,
   -0.003406524658203125,
   0.02545166015625,
   0.005741119384765625,
   0.0301055908203125,
   0.03692626953125,
   0.0033588409423828125,
   0.0292816162109375,
   0.052520751953125,
   -0.01363372802734375,
   0.04327392578125,
   0.01316070556640625,
   -0.001049041748046875,
   -0.05859375,
   -0.0204315185546875,
   -0.0028095245361328125,
   -0.02740478515625,
   -0.049957275390625,
   0.048919677734375,
   -0.054168701171875,
   0.01275634765625,
   -0.02154541015625,
   0.0321044921875,
   0.0028018951416015625,
   -0.020751953125,
   -0.036102294921875,
   0.041717529296875,
   0.040496826171875,
   -0.01026153564453125,
   -0.042327880859375,
   0.0203399658203125,
   0.0041656494140625,
   0.035247802734375,
   -0.024505615234375,
   0.0135345458984375,
   -0.01224517822265625,
   0.01666259765625,
   -0.059814453125,
   0.0003037452697753906,
   -0.0027523040771484375,
   0.0083160400390625,
   -0.03369140625,
   0.0670166015625,
   0.00690460205078125,
   -0.0826416015625,
   -0.013275146484375,
   0.0244293212890625,
   0.02789306640625,
   -0.017822265625,
   -0.06610107421875,
   0.04644775390625,
   -0.0075225830078125,
   0.01299285888671875,
   0.0030670166015625,
   -0.033294677734375,
   0.004871368408203125,
   0.00266265869140625,
   -0.017669677734375,
   0.051055908203125,
   0.0233917236328125,
   -0.004734039306640625,
   -0.024261474609375,
   0.0120849609375,
   0.00847625732421875,
   0.005924224853515625,
   0.0131072998046875,
   -0.017974853515625,
   0.030487060546875,
   0.01515960693359375,
   0.01837158203125,
   -0.0125579833984375,
   0.0154266357421875,
   -0.00914764404296875,
   -0.00878143310546875,
   -0.0158233642578125,
   0.027191162109375,
   0.0212860107421875,
   -0.020050048828125,
   0.055084228515625,
   0.055633544921875,
   -0.0240325927734375,
   -0.00753021240234375,
   -0.01134490966796875,
   0.0711669921875,
   -0.01558685302734375,
   0.0157012939453125,
   -0.056182861328125,
   0.023590087890625,
   -0.0247039794921875,
   -0.008544921875,
   -0.025390625,
   -0.0011434555053710938,
   -0.00868988037109375,
   -0.006866455078125,
   -0.0460205078125,
   -0.00930023193359375,
   0.0069427490234375,
   -0.01776123046875,
   0.0131072998046875,
   0.01399993896484375,
   0.01059722900390625,
   0.024566650390625,
   0.009368896484375,
   -0.039398193359375,
   -0.01776123046875,
   -0.0287017822265625,
   0.004604339599609375,
   -0.0137481689453125,
   0.025146484375,
   -0.016021728515625,
   0.0657958984375,
   -0.029296875,
   -0.025299072265625,
   -0.030975341796875,
   0.01505279541015625,
   -0.0335693359375,
   0.06805419921875,
   -0.00658416748046875,
   -0.0241851806640625,
   0.004131317138671875,
   -0.0162353515625,
   0.007083892822265625,
   -0.011474609375,
   0.006195068359375,
   -0.03338623046875,
   0.0105133056640625,
   0.00809478759765625,
   0.01165771484375,
   -0.0045166015625,
   -0.0118865966796875,
   0.0165557861328125,
   0.02801513671875,
   0.0165863037109375,
   -0.049285888671875,
   -0.01837158203125,
   0.006622314453125,
   0.00797271728515625,
   0.0267181396484375,
   0.03558349609375,
   0.041534423828125,
   0.003879547119140625,
   -0.0057220458984375,
   0.01457977294921875,
   0.02813720703125,
   -0.0012388229370117188,
   0.0111083984375,
   0.014678955078125,
   0.016204833984375,
   0.03924560546875,
   -0.04779052734375,
   0.01122283935546875,
   0.0341796875,
   -0.0511474609375,
   -0.0014905929565429688,
   0.03179931640625,
   0.0003769397735595703,
   0.0035610198974609375,
   -0.00011026859283447266,
   -0.0005316734313964844,
   -0.0140838623046875,
   -0.0031757354736328125,
   -0.034912109375,
   -0.0208282470703125,
   -0.0195465087890625,
   -0.02734375,
   -0.03167724609375,
   0.00980377197265625,
   0.0093536376953125,
   -0.03399658203125,
   0.0182647705078125,
   0.016510009765625,
   -0.00576019287109375,
   0.01904296875,
   -0.01561737060546875,
   -0.0016107559204101562,
   -0.02099609375,
   -0.00396728515625,
   0.0270233154296875,
   -0.0179901123046875,
   -0.04583740234375,
   -0.01910400390625,
   -0.002498626708984375,
   0.0323486328125,
   -0.0008034706115722656,
   -0.018096923828125,
   -0.0073089599609375,
   -0.037872314453125,
   6.073713302612305e-05,
   0.016754150390625,
   -0.01849365234375,
   -0.041168212890625,
   0.01514434814453125,
   -0.06365966796875,
   -0.00911712646484375,
   0.004055023193359375,
   -0.0027561187744140625,
   -0.030029296875,
   -0.006683349609375,
   0.027191162109375,
   0.012481689453125,
   0.0299835205078125,
   -0.02294921875,
   0.00742340087890625,
   0.0268707275390625,
   0.048187255859375,
   0.0037822723388671875,
   0.0302581787109375,
   0.019134521484375,
   -0.0169219970703125,
   0.0286407470703125,
   -0.040924072265625,
   -0.0005373954772949219,
   -0.015045166015625,
   -0.00984954833984375,
   0.00356292724609375,
   -0.01131439208984375,
   0.0241241455078125,
   -0.0228424072265625,
   -0.0163116455078125,
   0.005107879638671875,
   -0.0273590087890625,
   -0.007236480712890625,
   -0.00445556640625,
   -1.7642974853515625e-05,
   0.0083770751953125,
   0.0064544677734375,
   -0.0308990478515625,
   -0.041595458984375,
   -0.00754547119140625,
   0.0046234130859375,
   0.0189971923828125,
   0.00960540771484375,
   0.0029449462890625,
   0.051300048828125,
   -0.0140838623046875,
   -0.0021991729736328125,
   0.027740478515625,
   -0.004100799560546875,
   0.0116424560546875,
   -0.004703521728515625,
   -0.0440673828125,
   0.02276611328125,
   -0.052825927734375,
   -0.00284576416015625,
   -0.038909912109375,
   0.01009368896484375,
   -0.0093536376953125,
   0.0145263671875,
   -0.007205963134765625,
   0.0186309814453125,
   0.0052490234375,
   0.01776123046875,
   -0.009429931640625,
   0.01546478271484375,
   0.005054473876953125,
   0.01207733154296875,
   -0.003875732421875,
   0.041839599609375,
   -0.021331787109375,
   0.01412200927734375,
   -0.043121337890625,
   -0.0012302398681640625,
   0.01454925537109375,
   0.0029811859130859375,
   0.0205841064453125,
   0.02984619140625,
   0.0207672119140625,
   -0.017822265625,
   0.0216217041015625,
   0.02911376953125,
   0.0133056640625,
   0.0098876953125,
   -0.0300445556640625,
   -0.0192718505859375,
   -0.0158538818359375,
   -0.004253387451171875,
   -0.008087158203125,
   0.01303863525390625,
   0.028961181640625,
   -0.024993896484375,
   -0.0166015625,
   -0.055450439453125,
   0.039398193359375,
   -0.00974273681640625,
   -0.0113067626953125,
   -0.04998779296875,
   0.0166168212890625,
   -0.0012464523315429688,
   -0.03204345703125,
   0.0187530517578125,
   -0.048248291015625,
   -0.00958251953125,
   -0.00945281982421875,
   0.0015153884887695312,
   0.043670654296875,
   -0.002880096435546875,
   0.0151214599609375,
   -0.020660400390625,
   0.01495361328125,
   0.016937255859375,
   0.0228424072265625,
   0.0191497802734375,
   0.036865234375,
   0.0008783340454101562,
   -0.0105438232421875,
   -0.01430511474609375,
   -0.0088958740234375,
   0.0102386474609375,
   -0.01611328125,
   0.0200347900390625,
   -0.0003037452697753906,
   0.00695037841796875,
   -0.01403045654296875,
   0.00443267822265625,
   0.05035400390625,
   -0.0172882080078125,
   0.0186614990234375,
   -0.0312347412109375,
   -0.005855560302734375,
   -0.006317138671875,
   -0.0672607421875,
   -0.0107421875,
   -0.017852783203125,
   -0.00417327880859375,
   -0.0111846923828125,
   -0.0010538101196289062,
   0.0018100738525390625,
   0.0168914794921875,
   0.0016622543334960938,
   -0.0145721435546875,
   -0.0007939338684082031,
   0.00786590576171875,
   -0.00862884521484375,
   -0.02362060546875,
   0.041778564453125,
   0.01165008544921875,
   0.015869140625,
   -0.00017464160919189453,
   -0.01084136962890625,
   -0.01474761962890625,
   -0.015716552734375,
   -0.01483917236328125,
   0.03314208984375,
   -0.027496337890625,
   0.0186920166015625,
   -0.0226898193359375,
   -0.03289794921875,
   -0.03143310546875,
   0.01212310791015625,
   0.0005674362182617188,
   -0.024932861328125,
   0.0002313852310180664,
   0.01195526123046875,
   0.00921630859375,
   0.0250701904296875,
   -0.0006422996520996094,
   0.01526641845703125,
   0.0217437744140625,
   -0.0162200927734375,
   0.0181732177734375,
   -0.0120849609375,
   -0.00592041015625,
   -0.03436279296875,
   0.04241943359375,
   0.0228729248046875,
   -0.02587890625,
   -0.0008478164672851562,
   -0.01111602783203125,
   0.00673675537109375,
   0.0103759765625,
   0.01480865478515625,
   -0.0158538818359375,
   0.029510498046875,
   -0.0002046823501586914,
   0.031890869140625,
   0.046905517578125,
   0.0546875,
   -0.0034332275390625,
   0.02581787109375,
   -0.01238250732421875,
   0.0093841552734375,
   -0.00846099853515625,
   -0.03143310546875,
   0.0029621124267578125,
   0.01861572265625,
   0.03802490234375,
   -0.0240020751953125,
   0.0226898193359375,
   0.006359100341796875,
   -0.03173828125,
   -0.077880859375,
   0.0596923828125,
   0.00690460205078125,
   -0.0157928466796875,
   0.006420135498046875,
   0.0158843994140625,
   0.021881103515625,
   0.048370361328125,
   0.0201416015625,
   0.034423828125,
   0.023345947265625,
   -0.0279693603515625,
   -0.01322174072265625,
   -0.0186004638671875,
   0.0286102294921875,
   0.0219573974609375,
   0.030426025390625,
   0.0175933837890625,
   -0.01971435546875,
   0.01334381103515625,
   -0.007244110107421875,
   -0.060455322265625,
   0.01441192626953125,
   0.031158447265625,
   -0.0222015380859375,
   0.025787353515625,
   -0.0125274658203125,
   0.0215301513671875,
   -0.015777587890625,
   -0.0026416778564453125,
   0.005489349365234375,
   -0.0105438232421875,
   -0.0209503173828125,
   0.0268096923828125,
   0.01093292236328125,
   -0.04779052734375,
   0.01039886474609375,
   0.02227783203125,
   -0.01457977294921875,
   0.02197265625,
   0.0096893310546875,
   0.0016717910766601562,
   -0.0184783935546875,
   0.0266265869140625,
   0.0016574859619140625,
   0.00628662109375,
   -0.0102691650390625,
   0.0189056396484375,
   -0.0457763671875,
   -0.0125579833984375,
   -0.01282501220703125,
   -0.0017347335815429688,
   0.00814056396484375,
   -0.039154052734375,
   0.035003662109375,
   0.00632476806640625,
   0.005207061767578125,
   0.0119171142578125,
   -0.004810333251953125,
   0.0006737709045410156,
   0.0185699462890625,
   -0.037750244140625,
   -0.01873779296875,
   -0.0020465850830078125,
   0.01177978515625,
   -0.01293182373046875,
   -0.00351715087890625,
   0.00937652587890625,
   0.036285400390625,
   0.004741668701171875,
   0.0205841064453125,
   -0.029449462890625,
   0.0017690658569335938,
   0.004642486572265625,
   -0.0175323486328125,
   0.01158905029296875,
   0.03582763671875,
   -0.035919189453125,
   0.018890380859375,
   0.049285888671875,
   -0.01727294921875,
   0.028289794921875,
   0.041656494140625,
   0.0031223297119140625,
   0.001918792724609375,
   0.0261993408203125,
   -0.0020580291748046875,
   -0.006107330322265625,
   -0.006580352783203125,
   -0.00909423828125,
   -0.037872314453125,
   0.00534820556640625,
   0.015625,
   0.0179290771484375,
   0.0210113525390625,
   -0.03863525390625,
   0.0118408203125,
   -0.0169525146484375,
   0.038299560546875,
   -0.051544189453125,
   -0.048187255859375,
   0.051361083984375,
   -0.0186614990234375,
   0.0197296142578125,
   -0.040191650390625,
   0.0024776458740234375,
   -0.016204833984375,
   0.0550537109375,
   0.00032329559326171875,
   0.056793212890625,
   0.0546875,
   -0.0219573974609375,
   -0.030059814453125,
   0.0045623779296875,
   -0.007205963134765625,
   0.021484375,
   -0.01154327392578125,
   0.010498046875,
   -0.004291534423828125,
   0.0137176513671875,
   -0.015533447265625,
   -0.003841400146484375,
   -0.006160736083984375,
   0.007659912109375,
   0.020294189453125,
   0.01195526123046875,
   -0.00392913818359375,
   0.0018739700317382812,
   0.0198516845703125,
   0.007038116455078125,
   0.035736083984375,
   0.00402069091796875,

In [100]:
print(retrived[0]['text'])

CHENNAI TRAVEL GUIDE
City/Country: Chennai, Tamil Nadu, India
Overview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.
Historical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.
Best months: November to February for relatively cooler sightseeing wea

In [101]:
print(retrived[0]['score'])
print(retrived[1]['score'])
print(retrived[2]['score'])

0.6145129644276335
0.6001106187203024
0.5483534654544384

In [102]:
print(retrived[0]['text'],retrived[0]['chunk_id'],retrived[0]['score'])

CHENNAI TRAVEL GUIDE
City/Country: Chennai, Tamil Nadu, India
Overview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.
Historical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.
Best months: November to February for relatively cooler sightseeing wea /voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0 0.6145129644276335

In [103]:
response=ask_rag(query, index)
response

{'question': 'What is the best month to visit Chennai from Chennai travel guide?',
 'answer': 'The best months to visit Chennai are from November to February for relatively cooler sightseeing weather [0].',
 'sources': ['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0',
  '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#1',
  '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#1'],
 'tokens_in': 412,
 'tokens_out': 19,
 'retrieved': [{'chunk_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0',
   'source_id': '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt',
   'text': 'CHENNAI TRAVEL GUIDE\nCity/Country: Chennai, Tamil Nadu, India\nOverview: Coastal capital on the Bay of Bengal and a major centre for Tamil culture, business, education and classical arts.\nHistorical note: The British East India Company established a settlement here in 1639; Fort St. George became an important colonial landmark.\nBest months: November to February for relatively cooler sightseeing wea',
   'vector': [0.06964111328125,
    -0.004734039306640625,
    0.0294952392578125,
    0.0154571533203125,
    0.0009036064147949219,
    -0.0091552734375,
    0.03558349609375,
    -0.032958984375,
    -0.056671142578125,
    0.02978515625,
    -0.040985107421875,
    0.0214080810546875,
    -0.0082244873046875,
    0.0005888938903808594,
    0.026123046875,
    0.0303802490234375,
    -0.042938232421875,
    -0.01206207275390625,
    0.0202484130859375,
    0.044403076171875,
    0.052764892578125,
    0.01947021484375,
    -0.0069580078125,
    -0.05780029296875,
    0.0224151611328125,
    0.03564453125,
    -0.0208892822265625,
    0.0219573974609375,
    -0.0211029052734375,
    0.0024261474609375,
    -0.0012845993041992188,
    0.0032863616943359375,
    0.054962158203125,
    -0.01250457763671875,
    0.0285797119140625,
    0.005458831787109375,
    0.0227813720703125,
    -0.0198822021484375,
    -0.0208740234375,
    -0.003376007080078125,
    0.032958984375,
    0.040374755859375,
    0.0335693359375,
    0.04058837890625,
    -0.00283050537109375,
    -0.004535675048828125,
    -0.06219482421875,
    0.04833984375,
    0.006763458251953125,
    -0.0311279296875,
    -0.0028438568115234375,
    -0.03118896484375,
    -0.0137939453125,
    0.020721435546875,
    -0.007259368896484375,
    -0.040374755859375,
    0.0264434814453125,
    0.029632568359375,
    -0.00830841064453125,
    -0.0166473388671875,
    0.02783203125,
    -0.0098876953125,
    -0.00489044189453125,
    0.0300445556640625,
    0.01114654541015625,
    0.0250701904296875,
    -0.047576904296875,
    0.04791259765625,
    -0.01319122314453125,
    0.0026378631591796875,
    0.0655517578125,
    -0.00949859619140625,
    -0.0017242431640625,
    -0.0147552490234375,
    -0.030426025390625,
    0.04376220703125,
    -0.033172607421875,
    -0.036468505859375,
    0.027557373046875,
    -0.0308990478515625,
    -0.06402587890625,
    0.028961181640625,
    0.00443267822265625,
    0.0169219970703125,
    -0.052978515625,
    -0.0022335052490234375,
    0.060333251953125,
    0.0121917724609375,
    -0.018798828125,
    0.0262908935546875,
    0.0175628662109375,
    -0.02166748046875,
    0.0174407958984375,
    0.021026611328125,
    0.042938232421875,
    0.006649017333984375,
    0.01519775390625,
    0.0047149658203125,
    0.03045654296875,
    0.06005859375,
    0.01885986328125,
    -0.03466796875,
    -0.032562255859375,
    0.0032138824462890625,
    0.07061767578125,
    0.01293182373046875,
    -0.019622802734375,
    -0.0032215118408203125,
    0.016845703125,
    -0.02008056640625,
    -0.0684814453125,
    0.003925323486328125,
    0.0015878677368164062,
    0.03680419921875,
    -0.01233673095703125,
    -0.03173828125,
    0.060516357421875,
    -0.071533203125,
    -0.01122283935546875,
    0.01556396484375,
    -0.0280303955078125,
    -0.01332855224609375,
    0.007175445556640625,
    -0.01543426513671875,
    -0.0416259765625,
    -0.0697021484375,
    -0.0030364990234375,
    0.0308380126953125,
    0.0261383056640625,
    -0.0178985595703125,
    0.015228271484375,
    0.00927734375,
    -0.00980377197265625,
    -0.02947998046875,
    0.008758544921875,
    -0.03753662109375,
    -0.036041259765625,
    0.00026345252990722656,
    -0.01006317138671875,
    0.033050537109375,
    0.0313720703125,
    -0.01605224609375,
    -0.0181732177734375,
    0.0270538330078125,
    0.007083892822265625,
    -0.029388427734375,
    -0.032318115234375,
    0.0491943359375,
    0.0309600830078125,
    0.00432586669921875,
    0.0037441253662109375,
    0.0102996826171875,
    0.0205230712890625,
    0.00011754035949707031,
    0.0032978057861328125,
    -0.0238494873046875,
    -0.023773193359375,
    0.011627197265625,
    -0.049591064453125,
    -0.0254058837890625,
    -0.04266357421875,
    -0.009521484375,
    -0.0255279541015625,
    -0.004222869873046875,
    -0.01165008544921875,
    -0.0389404296875,
    -0.07958984375,
    0.0125732421875,
    -0.050079345703125,
    0.0181427001953125,
    0.0128173828125,
    -0.0180511474609375,
    0.0162811279296875,
    0.021575927734375,
    0.048492431640625,
    0.025146484375,
    0.0174560546875,
    -0.06829833984375,
    -0.054412841796875,
    -0.00039887428283691406,
    -0.041717529296875,
    -0.0033321380615234375,
    -0.0021457672119140625,
    -0.006198883056640625,
    0.0023632049560546875,
    0.015289306640625,
    -0.0012073516845703125,
    0.006259918212890625,
    -0.0194244384765625,
    0.0238189697265625,
    -0.0173797607421875,
    -0.01415252685546875,
    0.00350189208984375,
    -0.0017881393432617188,
    -0.02734375,
    -0.0272216796875,
    0.01491546630859375,
    -0.034271240234375,
    0.00508880615234375,
    -0.03125,
    0.024932861328125,
    -0.030029296875,
    -0.006168365478515625,
    0.010406494140625,
    -0.052215576171875,
    -0.0132293701171875,
    0.047271728515625,
    0.03106689453125,
    0.002777099609375,
    0.0237274169921875,
    0.035064697265625,
    -0.0189361572265625,
    -0.0207672119140625,
    -0.0178680419921875,
    0.0208282470703125,
    0.015716552734375,
    -0.04132080078125,
    -0.0357666015625,
    -0.0211334228515625,
    -0.02264404296875,
    -0.0265960693359375,
    0.005840301513671875,
    0.009033203125,
    0.00449371337890625,
    -0.006855010986328125,
    0.005725860595703125,
    -0.0330810546875,
    0.0288848876953125,
    0.01313018798828125,
    -0.038970947265625,
    0.00513458251953125,
    -0.032928466796875,
    0.0270843505859375,
    -0.0260467529296875,
    -0.0150299072265625,
    -0.0477294921875,
    0.0933837890625,
    0.0225372314453125,
    0.00579071044921875,
    -0.0195465087890625,
    -0.0477294921875,
    0.035308837890625,
    -0.0012302398681640625,
    0.015350341796875,
    0.01033782958984375,
    -0.0153656005859375,
    -0.013275146484375,
    -0.001598358154296875,
    0.025543212890625,
    0.0187530517578125,
    0.022369384765625,
    0.0367431640625,
    0.01255035400390625,
    -0.041168212890625,
    0.008697509765625,
    0.0150146484375,
    -0.0204925537109375,
    -0.010009765625,
    -0.0111541748046875,
    -0.051544189453125,
    -0.0306549072265625,
    0.0233917236328125,
    0.0145111083984375,
    -0.072265625,
    0.0032176971435546875,
    0.004451751708984375,
    -0.019744873046875,
    -0.005603790283203125,
    0.0006961822509765625,
    -0.045654296875,
    -0.0189361572265625,
    -0.020294189453125,
    0.008392333984375,
    -0.05657958984375,
    -0.0439453125,
    -0.010345458984375,
    -0.03692626953125,
    0.0022830963134765625,
    -0.0297088623046875,
    0.01561737060546875,
    0.0014600753784179688,
    0.00879669189453125,
    -0.0248565673828125,
    6.091594696044922e-05,
    -0.0311126708984375,
    0.00960540771484375,
    0.0284881591796875,
    -0.0015649795532226562,
    0.01377105712890625,
    -0.0024013519287109375,
    0.04278564453125,
    -0.020599365234375,
    -0.0099945068359375,
    0.0250396728515625,
    0.0221405029296875,
    0.00750732421875,
    -0.035125732421875,
    -0.01303863525390625,
    0.060089111328125,
    -0.036956787109375,
    -0.02679443359375,
    -0.006748199462890625,
    -0.044036865234375,
    -0.0154571533203125,
    0.005954742431640625,
    0.03173828125,
    -0.03192138671875,
    -0.01398468017578125,
    -0.00315093994140625,
    0.0301971435546875,
    -0.0175323486328125,
    -0.01181793212890625,
    0.0205230712890625,
    -0.03350830078125,
    -0.040435791015625,
    -0.0213623046875,
    0.00408172607421875,
    -0.00550079345703125,
    -0.003406524658203125,
    0.02545166015625,
    0.005741119384765625,
    0.0301055908203125,
    0.03692626953125,
    0.0033588409423828125,
    0.0292816162109375,
    0.052520751953125,
    -0.01363372802734375,
    0.04327392578125,
    0.01316070556640625,
    -0.001049041748046875,
    -0.05859375,
    -0.0204315185546875,
    -0.0028095245361328125,
    -0.02740478515625,
    -0.049957275390625,
    0.048919677734375,
    -0.054168701171875,
    0.01275634765625,
    -0.02154541015625,
    0.0321044921875,
    0.0028018951416015625,
    -0.020751953125,
    -0.036102294921875,
    0.041717529296875,
    0.040496826171875,
    -0.01026153564453125,
    -0.042327880859375,
    0.0203399658203125,
    0.0041656494140625,
    0.035247802734375,
    -0.024505615234375,
    0.0135345458984375,
    -0.01224517822265625,
    0.01666259765625,
    -0.059814453125,
    0.0003037452697753906,
    -0.0027523040771484375,
    0.0083160400390625,
    -0.03369140625,
    0.0670166015625,
    0.00690460205078125,
    -0.0826416015625,
    -0.013275146484375,
    0.0244293212890625,
    0.02789306640625,
    -0.017822265625,
    -0.06610107421875,
    0.04644775390625,
    -0.0075225830078125,
    0.01299285888671875,
    0.0030670166015625,
    -0.033294677734375,
    0.004871368408203125,
    0.00266265869140625,
    -0.017669677734375,
    0.051055908203125,
    0.0233917236328125,
    -0.004734039306640625,
    -0.024261474609375,
    0.0120849609375,
    0.00847625732421875,
    0.005924224853515625,
    0.0131072998046875,
    -0.017974853515625,
    0.030487060546875,
    0.01515960693359375,
    0.01837158203125,
    -0.0125579833984375,
    0.0154266357421875,
    -0.00914764404296875,
    -0.00878143310546875,
    -0.0158233642578125,
    0.027191162109375,
    0.0212860107421875,
    -0.020050048828125,
    0.055084228515625,
    0.055633544921875,
    -0.0240325927734375,
    -0.00753021240234375,
    -0.01134490966796875,
    0.0711669921875,
    -0.01558685302734375,
    0.0157012939453125,
    -0.056182861328125,
    0.023590087890625,
    -0.0247039794921875,
    -0.008544921875,
    -0.025390625,
    -0.0011434555053710938,
    -0.00868988037109375,
    -0.006866455078125,
    -0.0460205078125,
    -0.00930023193359375,
    0.0069427490234375,
    -0.01776123046875,
    0.0131072998046875,
    0.01399993896484375,
    0.01059722900390625,
    0.024566650390625,
    0.009368896484375,
    -0.039398193359375,
    -0.01776123046875,
    -0.0287017822265625,
    0.004604339599609375,
    -0.0137481689453125,
    0.025146484375,
    -0.016021728515625,
    0.0657958984375,
    -0.029296875,
    -0.025299072265625,
    -0.030975341796875,
    0.01505279541015625,
    -0.0335693359375,
    0.06805419921875,
    -0.00658416748046875,
    -0.0241851806640625,
    0.004131317138671875,
    -0.0162353515625,
    0.007083892822265625,
    -0.011474609375,
    0.006195068359375,
    -0.03338623046875,
    0.0105133056640625,
    0.00809478759765625,
    0.01165771484375,
    -0.0045166015625,
    -0.0118865966796875,
    0.0165557861328125,
    0.02801513671875,
    0.0165863037109375,
    -0.049285888671875,
    -0.01837158203125,
    0.006622314453125,
    0.00797271728515625,
    0.0267181396484375,
    0.03558349609375,
    0.041534423828125,
    0.003879547119140625,
    -0.0057220458984375,
    0.01457977294921875,
    0.02813720703125,
    -0.0012388229370117188,
    0.0111083984375,
    0.014678955078125,
    0.016204833984375,
    0.03924560546875,
    -0.04779052734375,
    0.01122283935546875,
    0.0341796875,
    -0.0511474609375,
    -0.0014905929565429688,
    0.03179931640625,
    0.0003769397735595703,
    0.0035610198974609375,
    -0.00011026859283447266,
    -0.0005316734313964844,
    -0.0140838623046875,
    -0.0031757354736328125,
    -0.034912109375,
    -0.0208282470703125,
    -0.0195465087890625,
    -0.02734375,
    -0.03167724609375,
    0.00980377197265625,
    0.0093536376953125,
    -0.03399658203125,
    0.0182647705078125,
    0.016510009765625,
    -0.00576019287109375,
    0.01904296875,
    -0.01561737060546875,
    -0.0016107559204101562,
    -0.02099609375,
    -0.00396728515625,
    0.0270233154296875,
    -0.0179901123046875,
    -0.04583740234375,
    -0.01910400390625,
    -0.002498626708984375,
    0.0323486328125,
    -0.0008034706115722656,
    -0.018096923828125,
    -0.0073089599609375,
    -0.037872314453125,
    6.073713302612305e-05,
    0.016754150390625,
    -0.01849365234375,
    -0.041168212890625,
    0.01514434814453125,
    -0.06365966796875,
    -0.00911712646484375,
    0.004055023193359375,
    -0.0027561187744140625,
    -0.030029296875,
    -0.006683349609375,
    0.027191162109375,
    0.012481689453125,
    0.0299835205078125,
    -0.02294921875,
    0.00742340087890625,
    0.0268707275390625,
    0.048187255859375,
    0.0037822723388671875,
    0.0302581787109375,
    0.019134521484375,
    -0.0169219970703125,
    0.0286407470703125,
    -0.040924072265625,
    -0.0005373954772949219,
    -0.015045166015625,
    -0.00984954833984375,
    0.00356292724609375,
    -0.01131439208984375,
    0.0241241455078125,
    -0.0228424072265625,
    -0.0163116455078125,
    0.005107879638671875,
    -0.0273590087890625,
    -0.007236480712890625,
    -0.00445556640625,
    -1.7642974853515625e-05,
    0.0083770751953125,
    0.0064544677734375,
    -0.0308990478515625,
    -0.041595458984375,
    -0.00754547119140625,
    0.0046234130859375,
    0.0189971923828125,
    0.00960540771484375,
    0.0029449462890625,
    0.051300048828125,
    -0.0140838623046875,
    -0.0021991729736328125,
    0.027740478515625,
    -0.004100799560546875,
    0.0116424560546875,
    -0.004703521728515625,
    -0.0440673828125,
    0.02276611328125,
    -0.052825927734375,
    -0.00284576416015625,
    -0.038909912109375,
    0.01009368896484375,
    -0.0093536376953125,
    0.0145263671875,
    -0.007205963134765625,
    0.0186309814453125,
    0.0052490234375,
    0.01776123046875,
    -0.009429931640625,
    0.01546478271484375,
    0.005054473876953125,
    0.01207733154296875,
    -0.003875732421875,
    0.041839599609375,
    -0.021331787109375,
    0.01412200927734375,
    -0.043121337890625,
    -0.0012302398681640625,
    0.01454925537109375,
    0.0029811859130859375,
    0.0205841064453125,
    0.02984619140625,
    0.0207672119140625,
    -0.017822265625,
    0.0216217041015625,
    0.02911376953125,
    0.0133056640625,
    0.0098876953125,
    -0.0300445556640625,
    -0.0192718505859375,
    -0.0158538818359375,
    -0.004253387451171875,
    -0.008087158203125,
    0.01303863525390625,
    0.028961181640625,
    -0.024993896484375,
    -0.0166015625,
    -0.055450439453125,
    0.039398193359375,
    -0.00974273681640625,
    -0.0113067626953125,
    -0.04998779296875,
    0.0166168212890625,
    -0.0012464523315429688,
    -0.03204345703125,
    0.0187530517578125,
    -0.048248291015625,
    -0.00958251953125,
    -0.00945281982421875,
    0.0015153884887695312,
    0.043670654296875,
    -0.002880096435546875,
    0.0151214599609375,
    -0.020660400390625,
    0.01495361328125,
    0.016937255859375,
    0.0228424072265625,
    0.0191497802734375,
    0.036865234375,
    0.0008783340454101562,
    -0.0105438232421875,
    -0.01430511474609375,
    -0.0088958740234375,
    0.0102386474609375,
    -0.01611328125,
    0.0200347900390625,
    -0.0003037452697753906,
    0.00695037841796875,
    -0.01403045654296875,
    0.00443267822265625,
    0.05035400390625,
    -0.0172882080078125,
    0.0186614990234375,
    -0.0312347412109375,
    -0.005855560302734375,
    -0.006317138671875,
    -0.0672607421875,
    -0.0107421875,
    -0.017852783203125,
    -0.00417327880859375,
    -0.0111846923828125,
    -0.0010538101196289062,
    0.0018100738525390625,
    0.0168914794921875,
    0.0016622543334960938,
    -0.0145721435546875,
    -0.0007939338684082031,
    0.00786590576171875,
    -0.00862884521484375,
    -0.02362060546875,
    0.041778564453125,
    0.01165008544921875,
    0.015869140625,
    -0.00017464160919189453,
    -0.01084136962890625,
    -0.01474761962890625,
    -0.015716552734375,
    -0.01483917236328125,
    0.03314208984375,
    -0.027496337890625,
    0.0186920166015625,
    -0.0226898193359375,
    -0.03289794921875,
    -0.03143310546875,
    0.01212310791015625,
    0.0005674362182617188,
    -0.024932861328125,
    0.0002313852310180664,
    0.01195526123046875,
    0.00921630859375,
    0.0250701904296875,
    -0.0006422996520996094,
    0.01526641845703125,
    0.0217437744140625,
    -0.0162200927734375,
    0.0181732177734375,
    -0.0120849609375,
    -0.00592041015625,
    -0.03436279296875,
    0.04241943359375,
    0.0228729248046875,
    -0.02587890625,
    -0.0008478164672851562,
    -0.01111602783203125,
    0.00673675537109375,
    0.0103759765625,
    0.01480865478515625,
    -0.0158538818359375,
    0.029510498046875,
    -0.0002046823501586914,
    0.031890869140625,
    0.046905517578125,
    0.0546875,
    -0.0034332275390625,
    0.02581787109375,
    -0.01238250732421875,
    0.0093841552734375,
    -0.00846099853515625,
    -0.03143310546875,
    0.0029621124267578125,
    0.01861572265625,
    0.03802490234375,
    -0.0240020751953125,
    0.0226898193359375,
    0.006359100341796875,
    -0.03173828125,
    -0.077880859375,
    0.0596923828125,
    0.00690460205078125,
    -0.0157928466796875,
    0.006420135498046875,
    0.0158843994140625,
    0.021881103515625,
    0.048370361328125,
    0.0201416015625,
    0.034423828125,
    0.023345947265625,
    -0.0279693603515625,
    -0.01322174072265625,
    -0.0186004638671875,
    0.0286102294921875,
    0.0219573974609375,
    0.030426025390625,
    0.0175933837890625,
    -0.01971435546875,
    0.01334381103515625,
    -0.007244110107421875,
    -0.060455322265625,
    0.01441192626953125,
    0.031158447265625,
    -0.0222015380859375,
    0.025787353515625,
    -0.0125274658203125,
    0.0215301513671875,
    -0.015777587890625,
    -0.0026416778564453125,
    0.005489349365234375,
    -0.0105438232421875,
    -0.0209503173828125,
    0.0268096923828125,
    0.01093292236328125,
    -0.04779052734375,
    0.01039886474609375,
    0.02227783203125,
    -0.01457977294921875,
    0.02197265625,
    0.0096893310546875,
    0.0016717910766601562,
    -0.0184783935546875,
    0.0266265869140625,
    0.0016574859619140625,
    0.00628662109375,
    -0.0102691650390625,
    0.0189056396484375,
    -0.0457763671875,
    -0.0125579833984375,
    -0.01282501220703125,
    -0.0017347335815429688,
    0.00814056396484375,
    -0.039154052734375,
    0.035003662109375,
    0.00632476806640625,
    0.005207061767578125,
    0.0119171142578125,
    -0.004810333251953125,
    0.0006737709045410156,
    0.0185699462890625,
    -0.037750244140625,
    -0.01873779296875,
    -0.0020465850830078125,
    0.01177978515625,
    -0.01293182373046875,
    -0.00351715087890625,
    0.00937652587890625,
    0.036285400390625,
    0.004741668701171875,
    0.0205841064453125,
    -0.029449462890625,
    0.0017690658569335938,

In [104]:
GOLDEN_SET = [
    {
        "id": "E01",
        "question": "Which months are considered the best time to visit Chennai?",
        "expected_answer": "November to February is considered the best time to visit Chennai.",
        "difficulty": "easy",
        "expected_sources": ["chennai_travel_guide.txt"]
    },
    {
        "id": "E02",
        "question": "Which airport serves Bengaluru?",
        "expected_answer": "Kempegowda International Airport serves Bengaluru.",
        "difficulty": "easy",
        "expected_sources": ["bangalore_travel_guide.txt"]
    },
    {
        "id": "E03",
        "question": "What is Mumbai known for as described in the travel guide?",
        "expected_answer": (
            "Mumbai is India's financial and entertainment capital and is known "
            "for colonial heritage, beaches, business and Bollywood culture."
        ),
        "difficulty": "easy",
        "expected_sources": ["mumbai_travel_guide.txt"]
    },
    {
        "id": "E04",
        "question": "Name two major heritage attractions mentioned in the Delhi travel guide.",
        "expected_answer": (
            "Any two of the following are correct: Red Fort, Qutub Minar, "
            "Humayun's Tomb, India Gate, Jama Masjid, Lotus Temple or Akshardham."
        ),
        "difficulty": "easy",
        "expected_sources": ["delhi_travel_guide.txt"]
    },
    {
        "id": "E05",
        "question": "In which year was Hyderabad founded according to the travel guide?",
        "expected_answer": "Hyderabad was founded in 1591.",
        "difficulty": "easy",
        "expected_sources": ["hyderabad_travel_guide.txt"]
    },
    {
        "id": "E06",
        "question": "Which area of Kochi is known for colonial streets and waterfront views?",
        "expected_answer": "Fort Kochi is known for colonial streets and waterfront views.",
        "difficulty": "easy",
        "expected_sources": ["kochi_travel_guide.txt"]
    },
    {
        "id": "E07",
        "question": "When did Goa join India according to the travel guide?",
        "expected_answer": "Goa joined India in 1961.",
        "difficulty": "easy",
        "expected_sources": ["goa_travel_guide.txt"]
    },
    {
        "id": "E08",
        "question": "In which year did Singapore become an independent republic?",
        "expected_answer": "Singapore became an independent republic in 1965.",
        "difficulty": "easy",
        "expected_sources": ["singapore_travel_guide.txt"]
    },
    {
        "id": "E09",
        "question": "What public transport card is commonly used across major public transport in Dubai?",
        "expected_answer": "Nol cards are used across major public transport in Dubai.",
        "difficulty": "easy",
        "expected_sources": ["dubai_travel_guide.txt"]
    },
    {
        "id": "E10",
        "question": "Which ancient settlement is London said to have developed from?",
        "expected_answer": "London developed from the Roman settlement of Londinium.",
        "difficulty": "easy",
        "expected_sources": ["london_travel_guide.txt"]
    },

    {
        "id": "M01",
        "question": (
            "Based on the distance examples in the Chennai guide, approximately "
            "how much farther is Mahabalipuram from Chennai than central Chennai "
            "is from Chennai Airport?"
        ),
        "expected_answer": (
            "Mahabalipuram is approximately 35 to 45 km farther from Chennai "
            "than central Chennai is from Chennai Airport."
        ),
        "difficulty": "medium",
        "expected_sources": ["chennai_travel_guide.txt"]
    },
    {
        "id": "M02",
        "question": (
            "Based on the Mumbai guide, which trip is likely to require more "
            "travel time: Gateway of India to Marine Drive or travelling from "
            "South Mumbai to Juhu?"
        ),
        "expected_answer": (
            "Travelling from South Mumbai to Juhu is likely to require more "
            "travel time because it is a longer journey and Mumbai traffic can "
            "be substantial."
        ),
        "difficulty": "medium",
        "expected_sources": ["mumbai_travel_guide.txt"]
    },
    {
        "id": "M03",
        "question": (
            "What is the combined approximate budget range for a 3-day budget "
            "trip to Hyderabad, excluding major shopping?"
        ),
        "expected_answer": "The approximate budget range is INR 6,000 to INR 13,500 for 3 days.",
        "difficulty": "medium",
        "expected_sources": ["hyderabad_travel_guide.txt"]
    },
    {
        "id": "M04",
        "question": (
            "According to the Singapore guide, approximately how far is Changi "
            "Airport from Marina Bay, and what is the approximate distance "
            "between Marina Bay and Gardens by the Bay?"
        ),
        "expected_answer": (
            "Changi Airport is approximately 20 km from Marina Bay by road, "
            "while Marina Bay and Gardens by the Bay are approximately 1-2 km apart."
        ),
        "difficulty": "medium",
        "expected_sources": ["singapore_travel_guide.txt"]
    },
    {
        "id": "M05",
        "question": (
            "Which Delhi attractions in the guide can be used to create a "
            "heritage-focused day that combines Mughal and older historic architecture?"
        ),
        "expected_answer": (
            "A suitable answer should include attractions such as the Red Fort, "
            "Humayun's Tomb, Qutub Minar and Jama Masjid."
        ),
        "difficulty": "medium",
        "expected_sources": ["delhi_travel_guide.txt"]
    },

    {
        "id": "H01",
        "question": "Which cities in the dataset are best visited between November and February?",
        "expected_answer": (
            "Chennai, Hyderabad and Goa explicitly list November to February "
            "as their best visiting period."
        ),
        "difficulty": "hard",
        "expected_sources": [
            "chennai_travel_guide.txt",
            "hyderabad_travel_guide.txt",
            "goa_travel_guide.txt"
        ]
    },
    {
        "id": "H02",
        "question": (
            "Which city has the shorter approximate airport-to-central-destination "
            "road distance: Singapore or Dubai, and by approximately how many kilometres?"
        ),
        "expected_answer": (
            "Dubai has the shorter distance. Dubai International Airport is "
            "approximately 15 km from Downtown Dubai compared with approximately "
            "20 km from Changi Airport to Marina Bay, so Dubai is shorter by approximately 5 km."
        ),
        "difficulty": "hard",
        "expected_sources": [
            "dubai_travel_guide.txt",
            "singapore_travel_guide.txt"
        ]
    },
    {
        "id": "H03",
        "question": (
            "Which destination has the lower estimated minimum daily budget, "
            "Chennai or London, and approximately how much lower is it when "
            "using the minimum values listed in each guide?"
        ),
        "expected_answer": (
            "Chennai has the lower estimated minimum daily budget. Chennai starts "
            "at INR 2,000 per day, while London starts at GBP 120 per day. "
            "The amounts are in different currencies and should not be directly "
            "subtracted without an exchange rate."
        ),
        "difficulty": "hard",
        "expected_sources": [
            "chennai_travel_guide.txt",
            "london_travel_guide.txt"
        ]
    },
    {
        "id": "H04",
        "question": (
            "Which two destinations in the dataset have strong colonial or British "
            "historical connections, and what are those connections?"
        ),
        "expected_answer": (
            "Chennai developed around the British East India Company's settlement "
            "established in 1639, while modern Singapore developed as a British "
            "trading port in 1819."
        ),
        "difficulty": "hard",
        "expected_sources": [
            "chennai_travel_guide.txt",
            "singapore_travel_guide.txt"
        ]
    },
    {
        "id": "H05",
        "question": (
            "If a traveller wants to visit a city founded in 1591, see a landmark "
            "built in the same year, and travel during the recommended cooler "
            "sightseeing season, which destination should they choose?"
        ),
        "expected_answer": (
            "Hyderabad. The city was founded in 1591, Charminar was built in 1591, "
            "and the recommended visiting period is October to February."
        ),
        "difficulty": "hard",
        "expected_sources": ["hyderabad_travel_guide.txt"]
    }
]

print(f"Loaded {len(GOLDEN_SET)} golden questions")

Loaded 20 golden questions

In [105]:
import json
import re
import time
import pandas as pd
from openai import OpenAI

client = OpenAI()

In [106]:
def extract_json(text):
    """
    Extract JSON from an LLM response.
    Handles plain JSON and JSON inside markdown fences.
    """
    if not text:
        return None

    text = text.strip()

    # Remove markdown fences
    text = re.sub(r"^```json\s*", "", text)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    # Find JSON object
    match = re.search(r"\{.*\}", text, re.DOTALL)

    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            return None

    return None

In [107]:
def evaluate_with_llm_judge(
    question,
    expected_answer,
    rag_answer,
    retrieved_sources,
    expected_sources,
    judge_model="gpt-4o-mini"
):
    """
    Evaluate RAG answer using LLM-as-Judge.

    Returns:
        answer_correctness: 1-5
        groundedness: 1-5
        citation_correctness: 1-5
        overall_score: 1-5
        explanation: text
    """

    prompt = f"""
You are an expert evaluator for a Retrieval-Augmented Generation (RAG) system.

Evaluate the RAG response against the golden reference.

QUESTION:
{question}

GOLDEN / EXPECTED ANSWER:
{expected_answer}

EXPECTED SOURCE DOCUMENTS:
{expected_sources}

RAG ANSWER:
{rag_answer}

SOURCE DOCUMENTS RETRIEVED BY RAG:
{retrieved_sources}

Evaluate using the following rules.

1. ANSWER_CORRECTNESS (1-5)
5 = Fully correct and contains the important facts from the expected answer.
4 = Mostly correct, with only a small omission or minor wording difference.
3 = Partially correct; important information is missing.
2 = Mostly incorrect.
1 = Incorrect, irrelevant, or hallucinated.

2. GROUNDEDNESS (1-5)
5 = Answer is clearly supported by the retrieved sources and does not introduce unsupported facts.
4 = Mostly grounded with a small unsupported inference.
3 = Mix of supported and unsupported claims.
2 = Mostly unsupported.
1 = Clearly hallucinated or unsupported.

IMPORTANT:
Groundedness should depend on whether the answer can reasonably be supported
by the retrieved documents, not just whether the answer happens to be correct.

3. CITATION_CORRECTNESS (1-5)
5 = All important expected source documents were retrieved.
4 = Most required sources were retrieved.
3 = Some required sources were retrieved.
2 = Retrieved sources are mostly wrong or irrelevant.
1 = No relevant expected source was retrieved.

4. OVERALL_SCORE (1-5)
Overall quality considering correctness, groundedness and retrieval quality.

IMPORTANT FOR MULTI-CURRENCY QUESTIONS:
If the golden answer says currencies must NOT be directly subtracted without an
exchange rate, the RAG answer must recognize that. Penalize an answer that
performs an invalid direct subtraction across currencies.

Return ONLY valid JSON in this exact format:

{{
    "answer_correctness": 1,
    "groundedness": 1,
    "citation_correctness": 1,
    "overall_score": 1,
    "explanation": "short explanation"
}}
"""

    try:
        response = client.chat.completions.create(
            model=judge_model,
            messages=[
                {
                    "role": "system",
                    "content": "You are a strict and unbiased RAG evaluation judge."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0,
            response_format={"type": "json_object"}
        )

        result = json.loads(response.choices[0].message.content)

        return result

    except Exception as e:
        print(f"Judge error: {e}")

        return {
            "answer_correctness": None,
            "groundedness": None,
            "citation_correctness": None,
            "overall_score": None,
            "explanation": f"Judge failed: {str(e)}"
        }

In [108]:
def calculate_retrieval_metrics(expected_sources, retrieved_sources):
    """
    Calculate deterministic retrieval KPIs.
    """

    expected_set = set(expected_sources)
    retrieved_set = set(retrieved_sources)

    matched_sources = expected_set.intersection(retrieved_set)

    # At least one expected document retrieved
    retrieval_hit = len(matched_sources) > 0

    # Percentage of required documents retrieved
    source_recall = (
        len(matched_sources) / len(expected_set)
        if expected_set else 0
    )

    # Precision of retrieved source documents
    source_precision = (
        len(matched_sources) / len(retrieved_set)
        if retrieved_set else 0
    )

    # Did we retrieve every expected source?
    all_expected_sources_retrieved = expected_set.issubset(retrieved_set)

    return {
        "retrieval_hit": retrieval_hit,
        "source_recall": source_recall,
        "source_precision": source_precision,
        "all_expected_sources_retrieved": all_expected_sources_retrieved,
        "matched_sources": list(matched_sources)
    }

In [109]:
def run_golden_set_evaluation(
    golden_set,
    index,
    k=5,
    judge_model="gpt-4o-mini"
):
    results = []

    total_questions = len(golden_set)

    print(f"Running evaluation for {total_questions} questions...\n")

    for i, item in enumerate(golden_set, 1):

        question_id = item["id"]
        question = item["question"]

        print("=" * 100)
        print(
            f"[{i}/{total_questions}] "
            f"{question_id} | {item['difficulty'].upper()}"
        )
        print(f"Question: {question}")

        # -------------------------------------------------------
        # 1. Ask RAG
        # -------------------------------------------------------
        start_time = time.time()

        rag_response = ask_rag(
            question,
            index,
            k=k
        )

        latency = time.time() - start_time

        rag_answer = rag_response.get("answer", "")

        # Sources returned by your ask_rag implementation
        retrieved_sources = rag_response.get("sources", [])

        # Remove duplicates while preserving order
        retrieved_sources = list(dict.fromkeys(retrieved_sources))

        # -------------------------------------------------------
        # 2. Calculate deterministic retrieval metrics
        # -------------------------------------------------------
        retrieval_metrics = calculate_retrieval_metrics(
            item["expected_sources"],
            retrieved_sources
        )

        # -------------------------------------------------------
        # 3. LLM as Judge
        # -------------------------------------------------------
        judge_result = evaluate_with_llm_judge(
            question=question,
            expected_answer=item["expected_answer"],
            rag_answer=rag_answer,
            retrieved_sources=retrieved_sources,
            expected_sources=item["expected_sources"],
            judge_model=judge_model
        )

        # -------------------------------------------------------
        # 4. Cost
        # -------------------------------------------------------
        try:
            rag_cost = cost_usd(rag_response)
        except Exception:
            rag_cost = None

        # -------------------------------------------------------
        # 5. Save result
        # -------------------------------------------------------
        result = {
            "id": question_id,
            "difficulty": item["difficulty"],
            "question": question,
            "expected_answer": item["expected_answer"],
            "rag_answer": rag_answer,

            "expected_sources": ", ".join(item["expected_sources"]),
            "retrieved_sources": ", ".join(retrieved_sources),

            "retrieval_hit": retrieval_metrics["retrieval_hit"],
            "source_recall": retrieval_metrics["source_recall"],
            "source_precision": retrieval_metrics["source_precision"],
            "all_expected_sources_retrieved":
                retrieval_metrics["all_expected_sources_retrieved"],
            "matched_sources": ", ".join(
                retrieval_metrics["matched_sources"]
            ),

            "answer_correctness":
                judge_result.get("answer_correctness"),
            "groundedness":
                judge_result.get("groundedness"),
            "citation_correctness":
                judge_result.get("citation_correctness"),
            "overall_score":
                judge_result.get("overall_score"),
            "judge_explanation":
                judge_result.get("explanation"),

            "latency_s": latency,
            "cost_usd": rag_cost,

            "tokens_in": rag_response.get("tokens_in"),
            "tokens_out": rag_response.get("tokens_out")
        }

        results.append(result)

        # -------------------------------------------------------
        # Print result
        # -------------------------------------------------------
        print(f"\nRAG Answer:")
        print(rag_answer)

        print(f"\nExpected Sources:")
        print(item["expected_sources"])

        print(f"\nRetrieved Sources:")
        print(retrieved_sources)

        print(f"\nKPIs:")
        print(
            f"  Retrieval Hit: "
            f"{retrieval_metrics['retrieval_hit']}"
        )
        print(
            f"  Source Recall: "
            f"{retrieval_metrics['source_recall'] * 100:.1f}%"
        )
        print(
            f"  Answer Correctness: "
            f"{judge_result.get('answer_correctness')}/5"
        )
        print(
            f"  Groundedness: "
            f"{judge_result.get('groundedness')}/5"
        )
        print(
            f"  Citation Correctness: "
            f"{judge_result.get('citation_correctness')}/5"
        )
        print(
            f"  Overall Score: "
            f"{judge_result.get('overall_score')}/5"
        )
        print(f"  Latency: {latency:.2f}s")

    return pd.DataFrame(results)

In [110]:
results_df = run_golden_set_evaluation(
    golden_set=GOLDEN_SET,
    index=index,
    k=5,
    judge_model="gpt-4o-mini"
)

results_df.head()

Running evaluation for 20 questions...

====================================================================================================
[1/20] E01 | EASY
Question: Which months are considered the best time to visit Chennai?

RAG Answer:
The best months to visit Chennai are from November to February for relatively cooler sightseeing weather [source id: 0].

Expected Sources:
['chennai_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#1']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.45s
====================================================================================================
[2/20] E02 | EASY
Question: Which airport serves Bengaluru?

RAG Answer:
The airport that serves Bengaluru is Kempegowda International Airport [3].

Expected Sources:
['bangalore_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#4']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.54s
====================================================================================================
[3/20] E03 | EASY
Question: What is Mumbai known for as described in the travel guide?

RAG Answer:
Mumbai is known for being India's financial and entertainment capital, combining colonial heritage, beaches, business, and Bollywood culture [0].

Expected Sources:
['mumbai_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#5']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.22s
====================================================================================================
[4/20] E04 | EASY
Question: Name two major heritage attractions mentioned in the Delhi travel guide.

RAG Answer:
Two major heritage attractions mentioned in the Delhi travel guide are Qutub Minar and Humayun's Tomb [source id: 1].

Expected Sources:
['delhi_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#3']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.51s
====================================================================================================
[5/20] E05 | EASY
Question: In which year was Hyderabad founded according to the travel guide?

RAG Answer:
Hyderabad was founded in 1591 according to the travel guide [0].

Expected Sources:
['hyderabad_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#3']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.19s
====================================================================================================
[6/20] E06 | EASY
Question: Which area of Kochi is known for colonial streets and waterfront views?

RAG Answer:
Fort Kochi is known for colonial streets and waterfront views [source id: 1].

Expected Sources:
['kochi_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#4']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.14s
====================================================================================================
[7/20] E07 | EASY
Question: When did Goa join India according to the travel guide?

RAG Answer:
Goa joined India in 1961 according to the travel guide [5].

Expected Sources:
['goa_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/goa_travel_guide.txt#4']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.17s
====================================================================================================
[8/20] E08 | EASY
Question: In which year did Singapore become an independent republic?

RAG Answer:
Singapore became an independent republic in 1965 [5].

Expected Sources:
['singapore_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#2']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.14s
====================================================================================================
[9/20] E09 | EASY
Question: What public transport card is commonly used across major public transport in Dubai?

RAG Answer:
The public transport card commonly used across major public transport in Dubai is the Nol card [4].

Expected Sources:
['dubai_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#0']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.35s
====================================================================================================
[10/20] E10 | EASY
Question: Which ancient settlement is London said to have developed from?

RAG Answer:
London is said to have developed from the ancient settlement of Roman Londinium [source id: #0].

Expected Sources:
['london_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#6', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#4']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.46s
====================================================================================================
[11/20] M01 | MEDIUM
Question: Based on the distance examples in the Chennai guide, approximately how much farther is Mahabalipuram from Chennai than central Chennai is from Chennai Airport?

RAG Answer:
The distance from Chennai to Mahabalipuram is about 55-60 km, and the distance from Chennai Airport to central Chennai is roughly 15-20 km.

To find the difference, we can take the maximum distances:
- Mahabalipuram: 60 km
- Central Chennai from Airport: 20 km

So, 60 km - 20 km = 40 km.

Therefore, Mahabalipuram is approximately 40 km farther from Chennai than central Chennai is from Chennai Airport.

Expected Sources:
['chennai_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#6']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 4/5
  Groundedness: 4/5
  Citation Correctness: 5/5
  Overall Score: 4/5
  Latency: 2.06s
====================================================================================================
[12/20] M02 | MEDIUM
Question: Based on the Mumbai guide, which trip is likely to require more travel time: Gateway of India to Marine Drive or travelling from South Mumbai to Juhu?

RAG Answer:
Traveling from South Mumbai to Juhu can take substantial time because of traffic, while the distance from Gateway of India to Marine Drive is about 4-5 km by road. Therefore, the trip from South Mumbai to Juhu is likely to require more travel time. [source id: 4]

Expected Sources:
['mumbai_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#2']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.70s
====================================================================================================
[13/20] M03 | MEDIUM
Question: What is the combined approximate budget range for a 3-day budget trip to Hyderabad, excluding major shopping?

RAG Answer:
The combined approximate budget range for a 3-day budget trip to Hyderabad is INR 6,000 to 13,500 (INR 2,000-4,500/day for 3 days totals INR 6,000-13,500) [4].

Expected Sources:
['hyderabad_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/hyderabad_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#5']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.74s
====================================================================================================
[14/20] M04 | MEDIUM
Question: According to the Singapore guide, approximately how far is Changi Airport from Marina Bay, and what is the approximate distance between Marina Bay and Gardens by the Bay?

RAG Answer:
Changi Airport is roughly 20 km from Marina Bay. The distance between Marina Bay and Gardens by the Bay is about 1-2 km depending on the exact points [4].

Expected Sources:
['singapore_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#0']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.44s
====================================================================================================
[15/20] M05 | MEDIUM
Question: Which Delhi attractions in the guide can be used to create a heritage-focused day that combines Mughal and older historic architecture?

RAG Answer:
For a heritage-focused day in Delhi that combines Mughal and older historic architecture, you can visit the following attractions mentioned in the guide:

1. Red Fort
2. Qutub Minar
3. Humayun's Tomb
4. Jama Masjid

These sites reflect the Mughal heritage and older historic architecture of Delhi. [source id: 1, 5]

Expected Sources:
['delhi_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#0', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#2', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#4']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 5/5
  Overall Score: 5/5
  Latency: 1.82s
====================================================================================================
[16/20] H01 | HARD
Question: Which cities in the dataset are best visited between November and February?

RAG Answer:
The cities in the dataset that are best visited between November and February are Chennai and Dubai. [1][4]

Expected Sources:
['chennai_travel_guide.txt', 'hyderabad_travel_guide.txt', 'goa_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/bangalore_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#1', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#1']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 2/5
  Groundedness: 2/5
  Citation Correctness: 2/5
  Overall Score: 2/5
  Latency: 1.41s
====================================================================================================
[17/20] H02 | HARD
Question: Which city has the shorter approximate airport-to-central-destination road distance: Singapore or Dubai, and by approximately how many kilometres?

RAG Answer:
Dubai has a shorter approximate airport-to-central-destination road distance of roughly 15 km from Dubai International Airport to Downtown Dubai, compared to Singapore's Changi Airport, which is roughly 20 km from Changi Airport to Marina Bay. Therefore, Dubai's distance is shorter by approximately 5 km. [4]

Expected Sources:
['dubai_travel_guide.txt', 'singapore_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/singapore_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/dubai_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/mumbai_travel_guide.txt#4', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#3']

KPIs:
  Retrieval Hit: False
  Source Recall: 0.0%
  Answer Correctness: 5/5
  Groundedness: 5/5
  Citation Correctness: 4/5
  Overall Score: 5/5
  Latency: 1.58s
====================================================================================================
[18/20] H03 | HARD
Question: Which destination has the lower estimated minimum daily budget, Chennai or London, and approximately how much lower is it when using the minimum values listed in each guide?

RAG Answer:
Chennai has the lower estimated minimum daily budget at INR 2,000-4,000/day, while London has a budget of GBP 120-220/day. To compare the minimum values, we need to convert the currencies.

Assuming an approximate exchange rate of 1 GBP = 100 INR (for simplicity), the minimum budget for London would be around INR 12,000 (GBP 120).

Therefore, the difference in the minimum daily budget is:
INR 12,000 (London) - INR 2,000 (Chennai) = INR 10,000.

Chennai's budget is approximately INR 10,000 lower than London's minimum daily budget.

Expected Sources:
['chennai_travel_guide.txt', 'london_travel_guide.txt']

Retrieved Sources:
['/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/london_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/chennai_travel_guide.txt#3', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/kochi_travel_guide.txt#5', '/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/ShortFormatFiles/delhi_travel_guide.txt#5']


,id,difficulty,question,expected_answer,rag_answer,expected_sources,retrieved_sources,retrieval_hit,source_recall,source_precision,...,matched_sources,answer_correctness,groundedness,citation_correctness,overall_score,judge_explanation,latency_s,cost_usd,tokens_in,tokens_out
0,E01,easy,Which months are considered the best time to v...,November to February is considered the best ti...,The best months to visit Chennai are from Nove...,chennai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,0.0,...,,5,5,5,5,The RAG answer correctly identifies the best m...,1.452698,0.000113,661,23
1,E02,easy,Which airport serves Bengaluru?,Kempegowda International Airport serves Bengal...,The airport that serves Bengaluru is Kempegowd...,bangalore_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,0.0,...,,5,5,5,5,The RAG answer correctly identifies Kempegowda...,1.539631,0.000108,658,15
2,E03,easy,What is Mumbai known for as described in the t...,Mumbai is India's financial and entertainment ...,Mumbai is known for being India's financial an...,mumbai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,0.0,...,,5,5,5,5,The RAG answer accurately reflects the key poi...,1.223833,0.000115,669,25
3,E04,easy,Name two major heritage attractions mentioned ...,Any two of the following are correct: Red Fort...,Two major heritage attractions mentioned in th...,delhi_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,0.0,...,,5,5,5,5,The RAG answer correctly identifies two major ...,1.511789,0.000120,686,28
4,E05,easy,In which year was Hyderabad founded according ...,Hyderabad was founded in 1591.,Hyderabad was founded in 1591 according to the...,hyderabad_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,0.0,...,,5,5,5,5,"The RAG answer is fully correct, accurately st...",1.185576,0.000110,670,16

In [111]:
overall_kpis = {
    "Total Questions": len(results_df),

    "Answer Correctness (%)":
        results_df["answer_correctness"].mean() / 5 * 100,

    "Groundedness (%)":
        results_df["groundedness"].mean() / 5 * 100,

    "Citation Correctness (%)":
        results_df["citation_correctness"].mean() / 5 * 100,

    "Overall LLM Judge Score (%)":
        results_df["overall_score"].mean() / 5 * 100,

    "Retrieval Hit Rate (%)":
        results_df["retrieval_hit"].mean() * 100,

    "Average Source Recall (%)":
        results_df["source_recall"].mean() * 100,

    "Average Source Precision (%)":
        results_df["source_precision"].mean() * 100,

    "All Required Sources Retrieved (%)":
        results_df["all_expected_sources_retrieved"].mean() * 100,

    "Average Latency (seconds)":
        results_df["latency_s"].mean(),

    "P50 Latency (seconds)":
        results_df["latency_s"].median(),

    "Total RAG Cost (USD)":
        results_df["cost_usd"].sum(),

    "Average Cost per Question (USD)":
        results_df["cost_usd"].mean()
}

overall_kpis_df = pd.DataFrame(
    list(overall_kpis.items()),
    columns=["KPI", "Value"]
)

overall_kpis_df

                                   KPI      Value
0                      Total Questions  20.000000
1               Answer Correctness (%)  87.000000
2                     Groundedness (%)  87.000000
3             Citation Correctness (%)  87.000000
4          Overall LLM Judge Score (%)  87.000000
5               Retrieval Hit Rate (%)   0.000000
6            Average Source Recall (%)   0.000000
7         Average Source Precision (%)   0.000000
8   All Required Sources Retrieved (%)   0.000000
9            Average Latency (seconds)   1.559711
10               P50 Latency (seconds)   1.487389
11                Total RAG Cost (USD)   0.002551
12     Average Cost per Question (USD)   0.000128

In [112]:
difficulty_summary = (
    results_df
    .groupby("difficulty")
    .agg(
        questions=("id", "count"),

        answer_correctness=("answer_correctness", "mean"),
        groundedness=("groundedness", "mean"),
        citation_correctness=("citation_correctness", "mean"),
        overall_score=("overall_score", "mean"),

        retrieval_hit_rate=("retrieval_hit", "mean"),
        source_recall=("source_recall", "mean"),

        avg_latency_s=("latency_s", "mean"),
        total_cost_usd=("cost_usd", "sum")
    )
    .round(4)
)

# Convert scores and rates to percentages
difficulty_summary["answer_correctness"] = (
    difficulty_summary["answer_correctness"] / 5 * 100
)

difficulty_summary["groundedness"] = (
    difficulty_summary["groundedness"] / 5 * 100
)

difficulty_summary["citation_correctness"] = (
    difficulty_summary["citation_correctness"] / 5 * 100
)

difficulty_summary["overall_score"] = (
    difficulty_summary["overall_score"] / 5 * 100
)

difficulty_summary["retrieval_hit_rate"] = (
    difficulty_summary["retrieval_hit_rate"] * 100
)

difficulty_summary["source_recall"] = (
    difficulty_summary["source_recall"] * 100
)

difficulty_summary

,questions,answer_correctness,groundedness,citation_correctness,overall_score,retrieval_hit_rate,source_recall,avg_latency_s,total_cost_usd
difficulty,,,,,,,,,
easy,10,100.0,100.0,100.0,100.0,0.0,0.0,1.3177,0.0011
hard,5,52.0,52.0,48.0,52.0,0.0,0.0,1.8532,0.0007
medium,5,96.0,96.0,100.0,96.0,0.0,0.0,1.7504,0.0007

In [113]:
failed_results = results_df[
    (
        results_df["answer_correctness"] < 4
    )
    |
    (
        results_df["groundedness"] < 4
    )
    |
    (
        results_df["retrieval_hit"] == False
    )
]

failed_results[
    [
        "id",
        "difficulty",
        "question",
        "rag_answer",
        "expected_sources",
        "retrieved_sources",
        "retrieval_hit",
        "source_recall",
        "answer_correctness",
        "groundedness",
        "citation_correctness",
        "overall_score",
        "judge_explanation"
    ]
]

,id,difficulty,question,rag_answer,expected_sources,retrieved_sources,retrieval_hit,source_recall,answer_correctness,groundedness,citation_correctness,overall_score,judge_explanation
0,E01,easy,Which months are considered the best time to v...,The best months to visit Chennai are from Nove...,chennai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly identifies the best m...
1,E02,easy,Which airport serves Bengaluru?,The airport that serves Bengaluru is Kempegowd...,bangalore_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly identifies Kempegowda...
2,E03,easy,What is Mumbai known for as described in the t...,Mumbai is known for being India's financial an...,mumbai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer accurately reflects the key poi...
3,E04,easy,Name two major heritage attractions mentioned ...,Two major heritage attractions mentioned in th...,delhi_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly identifies two major ...
4,E05,easy,In which year was Hyderabad founded according ...,Hyderabad was founded in 1591 according to the...,hyderabad_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,"The RAG answer is fully correct, accurately st..."
5,E06,easy,Which area of Kochi is known for colonial stre...,Fort Kochi is known for colonial streets and w...,kochi_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,"The RAG answer is fully correct, accurately st..."
6,E07,easy,When did Goa join India according to the trave...,Goa joined India in 1961 according to the trav...,goa_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,"The RAG answer is fully correct, directly matc..."
7,E08,easy,In which year did Singapore become an independ...,Singapore became an independent republic in 19...,singapore_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,"The RAG answer is fully correct, accurately st..."
8,E09,easy,What public transport card is commonly used ac...,The public transport card commonly used across...,dubai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly identifies the Nol ca...
9,E10,easy,Which ancient settlement is London said to hav...,London is said to have developed from the anci...,london_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,"The RAG answer is fully correct, accurately st..."
10,M01,medium,Based on the distance examples in the Chennai ...,The distance from Chennai to Mahabalipuram is ...,chennai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,4,4,5,4,"The RAG answer is mostly correct, as it provid..."
11,M02,medium,"Based on the Mumbai guide, which trip is likel...",Traveling from South Mumbai to Juhu can take s...,mumbai_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly identifies that trave...
12,M03,medium,What is the combined approximate budget range ...,The combined approximate budget range for a 3-...,hyderabad_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly states the budget ran...
13,M04,medium,"According to the Singapore guide, approximatel...",Changi Airport is roughly 20 km from Marina Ba...,singapore_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer accurately reflects the distanc...
14,M05,medium,Which Delhi attractions in the guide can be us...,For a heritage-focused day in Delhi that combi...,delhi_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,5,5,The RAG answer correctly lists all the attract...
15,H01,hard,Which cities in the dataset are best visited b...,The cities in the dataset that are best visite...,"chennai_travel_guide.txt, hyderabad_travel_gui...",/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,2,2,2,2,"The RAG answer incorrectly includes Dubai, whi..."
16,H02,hard,Which city has the shorter approximate airport...,Dubai has a shorter approximate airport-to-cen...,"dubai_travel_guide.txt, singapore_travel_guide...",/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,5,5,4,5,"The RAG answer is fully correct, providing the..."
17,H03,hard,Which destination has the lower estimated mini...,Chennai has the lower estimated minimum daily ...,"chennai_travel_guide.txt, london_travel_guide.txt",/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,4,4,4,4,The RAG answer correctly identifies that Chenn...
18,H04,hard,Which two destinations in the dataset have str...,The two destinations in the dataset with stron...,"chennai_travel_guide.txt, singapore_travel_gui...",/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,1,1,1,1,The RAG answer incorrectly identifies London a...
19,H05,hard,If a traveller wants to visit a city founded i...,"The traveller should choose Delhi, India. Delh...",hyderabad_travel_guide.txt,/voc/work/Demo Files/AI-RAG_W6_TrackAB_Bundle/...,False,0.0,1,1,1,1,The RAG answer incorrectly identifies Delhi as...

In [114]:
results_df.to_csv(
    "travel_rag_evaluation_results.csv",
    index=False
)

difficulty_summary.to_csv(
    "travel_rag_difficulty_summary.csv"
)

overall_kpis_df.to_csv(
    "travel_rag_overall_kpis.csv",
    index=False
)

print("Evaluation files saved successfully:")
print("1. travel_rag_evaluation_results.csv")
print("2. travel_rag_difficulty_summary.csv")
print("3. travel_rag_overall_kpis.csv")

Evaluation files saved successfully:
1. travel_rag_evaluation_results.csv
2. travel_rag_difficulty_summary.csv
3. travel_rag_overall_kpis.csv